### ISSUE TITLE
跳转页面后刷新浏览器，返回按钮功能失效

### ISSUE THREAD

**Issue by raisew** [imouou/BUI-Guide#10]
路由从一个页面跳转到另外一个页面，点击浏览器的刷新按钮页面刷新后，点击左上角的路由返回无效，请问这个有什么办法处理哦？

**Comment by imouou** [comment]
单页路由里有一个 reloadCache , 如果是webapp, 则可以开启这个为true, 这样这个后退路由就可以了. 但要记得调试时, 要改为false. 不然数据有可能结构不更新

**Comment by raisew** [comment]
谢谢你，问题已处理
