### ISSUE TITLE
var s= bui.storage(1000) 创建的存储 存储很大的数组数据，storage.get('')数据很卡

### ISSUE THREAD

**Issue by wuweiit** [imouou/BUI-Guide#100]
var s= bui.storage(1000) 创建的存储 存储很大的数组数据，storage.get('')数据很卡，性能较差；

我用原生的JSON.parse(localstorage.init); 却很快就执行了。

看不到源码也不能去分析原因，所以只能反馈出来了。

**Comment by imouou** [comment]
对的，这个问题我们也注意到了，后续新版会更新这个问题，之前考虑部分数据不是标准json格式，做了逐层判断转换，在多数据的时候，是存在这种问题的。

**Comment by imouou** [comment]
1.5.4 已经修复
