### ISSUE TITLE
如果将zepto.js替换为jQuery.js会有多大的影响？

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#101]
作者，你好。如果我将项目中依赖的zepto.js替换为最新版的jQuery.js会对项目中的哪些部分产生 影响？
原因：我想在项目中 依赖一些js库，但很多的js库都依赖于jQuery，例如我在引入jquery.timeago.js（一个描述过去时间的js库）时，该库依赖于data()函数，由于jQuery的data()函数可以存储对象，而zepto的data()函数只能存储字符串，所以导致该库在运行时不能达到想要的结果（其实现是将Date对象直接通过data()存储到DOM节点），遇到这种问题应该怎么办？

关于替换jQuery我的理解：zepto提供了一些方便移动端的api，但是BUI似乎并没有重度依赖，例如tap事件，BUI仍然推荐大家使用click事件。

希望作者能及时为我解惑，谢谢。

**Comment by imouou** [comment]
对的，BUI并没有重度依赖Zepto,目的也是为了能够方便切换功能更多的jQuery, 目前可以替换 jquery 1.1x 版本，问题不大，可以试试你的插件能不能依赖这个版本。

**Comment by shoppingzh** [comment]
好的，如果可能出现问题，那么会影响到BUI的哪些功能呢？能麻烦您简单描述一下吗？

**Comment by imouou** [comment]
bui只是用到一些extend 事件绑定 及常用的选择器而已，一般不会有影响，但1.1x 跟 2.x 之间变化太大，没具体对比过，一般使用1.1x 没什么问题的。
