### ISSUE TITLE
选项卡动态渲染

### ISSUE THREAD

**Issue by SoulChen1** [imouou/BUI-Guide#103]
根据官方文档的代码，无法显示动态渲染的效果！官方文档上也没有显示

**Comment by imouou** [comment]
可以的吧，具体可以查看单独的演示，文档的加载比较慢。 http://www.easybui.com/demo/#pages/ui_controls/bui.tab_head_dynamic  内容是由tab动态加载模板显示的，autoload 需要为true,参考该例子的源码

**Comment by SoulChen1** [comment]
右边为什么没有渲染出来呀，我需要动态的加载横向的选项卡




------------------ 原始邮件 ------------------
发件人: "王小o"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 下午2:04
收件人: "imouou/BUI-Guide"<BUI-Guide@noreply.github.com>;
抄送: "870964443"<870964443@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [imouou/BUI-Guide] 选项卡动态渲染 (#103)




可以的吧，具体可以查看单独的演示，文档的加载比较慢。 http://www.easybui.com/demo/#pages/ui_controls/bui.tab_head_dynamic  内容是由tab动态加载模板显示的，autoload 需要为true,参考该例子的源码

**Comment by imouou** [comment]
首先，我刚发的例子，能不能够动态加载呢？可以的话你本地例子不行，是因为本地请求有一些安全及跨域问题，先按文档的环境安装，跑一个服务，代码一样一定可以跑起来。
