### ISSUE TITLE
不使用main标签的时候该怎么写？能否给个demo

### ISSUE THREAD

**Issue by foxantony360** [imouou/BUI-Guide#106]
![image](https://user-images.githubusercontent.com/16914915/63233149-000d5200-c261-11e9-87ef-d2af111eb04e.png)
如图    这几个保留样式名就行   这句话没有看明白？保留样式名？

**Comment by imouou** [comment]
保留样式名你可以使用  ui-page 快速生成一个标准页面结构, 那里面的标签就是保留样式名
