### ISSUE TITLE
store组件中数组监听失败的问题

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#109]
作者，你好，我又来了。
近期我发现，当使用store组件时，数组的一些操作无法被捕捉到。请看下方的代码：
```
bui.store({
    scope: 'page',
    data: {
        userList: []
    },
    computed: {
        hasUser: function(){
            return this.userList.length;
        }
    }
});
// 代码省略：用户操作导致userList变化
// 如bs.userList.$replace(newList);
```
页面使用：`<span b-class="page.hasUser">User</span>`
这里的computed不是应该能监听到userList的变化吗？但是经过我的实验，发现并不能。同理，templates中如果使用到数组的相关操作，也不能及时更新视图。

文档中有明确说明.length操作可以监听到，可是这里为什么监听不到呢？如果是data下的某个字符串或数值变量，通过this.xxx的方式就可以监听到，只有数组才有这个问题。

请问，是不是我对此理解有偏差？麻烦解惑一下。

**Comment by imouou** [comment]
这个数组比较特殊, 需要使用对象的赋值操作才能在computed里面使用触发计算
```js
bui.store({
    scope: 'page',
    data: {
        userList: null
    },
    computed: {
        hasUser: function(){
            if( this.userList && this.userList.length ){
                 return true;
             }else{
                 return false;
             }
        }
    }
});
// 代码省略：用户操作导致userList变化
// 如bs.userList = newList;
```

**Comment by imouou** [comment]
但是如果你只是想做一个样式的操作, 一般无需这样操作, 直接控制 
```html
<span b-class="page.userList">User</span>
```
```js
var bs = bui.store({
    scope: 'page',
    data: {
        userList:[]
    }
});
```

`bs.userList.push("active")` 之类的去操作不是更简单吗, computed 一般用在 model 上

**Comment by shoppingzh** [comment]
我想实现的功能类似这样：
userList保存选择的结果，如果该数组不为空，则为某个元素增加或删除一个类名，这样只要userList发生了变化，此元素就能跟随变化，我只是想通过store让应用变得更加智能。

**Comment by imouou** [comment]
所以第一种就是可以通过赋值的方式来实现, 你return 出来可以是布尔值, 也可以是字符串, 如果是字符串则作为样式名. 接下来的增加都不用管这个数组, 只有清空的时候,才使用赋值 bs.userList = [] 就可以了.  

另外还有一种做法, 不过目前还不建议使用, <span b-class="page.hasUser" b-linked="page.userList">User</span>  为这两个创建关联, 这样数组的改变都会触发 hasUser 的改变

**Comment by imouou** [comment]
> 所以第一种就是可以通过赋值的方式来实现, 你return 出来可以是布尔值, 也可以是字符串, 如果是字符串则作为样式名. 接下来的增加都不用管这个数组, 只有清空的时候,才使用赋值 bs.userList = [] 就可以了.
> 
> 另外还有一种做法, 不过目前还不建议使用, User 为这两个创建关联, 这样数组的改变都会触发 hasUser 的改变

```html
<span b-class="page.hasUser" b-linked="page.userList">User</span>
```

**Comment by shoppingzh** [comment]
如果userList是通过checkbox选择的，那么必定有类似的代码：
`<input type="checkbox" b-model="page.userList">`
这时候userList是个model，根据用户选择，在页面上有不同的表现，如果用户选择了数据，则选择结果的DOM样式发生变化（例如背景从浅色变深色），私以为此时使用computed计算最为合适了：
```javascript
computed: {
    has: function(){
        return this.userList.length > 0;
    }
}
```
因为userList是通过用户操作自动设值的，因此捕捉checkbox事件的逻辑实际上发生在了store内部，在外部将不再捕捉checkbox的事件，那么也就无法判断userList是否发生了变化，此时还是需要借助store的一些特性，我想到的比较好的办法就是通过computed计算自动更新视图层的表现，但是奈何数组操作有一些不理解的表现。

另外请问一下，我在使用的过程中发现store与BUI的组件不搭（组件有自己的model，在组件内部），因此从来没有配合它们一起使用，此种做法是否合理？
使用过程中，我还发现store比较适合做筛选查询的场景（例如淘宝搜索页的右侧筛选），我在项目中大量使用到它进行筛选操作，请问这种思路是否正确？store还有更好的应用场景吗？目前我所发现的就是这一应用场景，我的理解是但凡有组件出现的地方使用store都会写出多余、难于理解且复杂度较高的代码。

**Comment by imouou** [comment]
也不全对, 虽然checkbox是在内部完成变化, 但是也别忘记了, computed 实际上用watch 也可以实现,  目前computed确实无法监听到数组读取length的变化能够导致视图更新, 后续的新版也仅仅支持第一层级的数组的长度读取可以触发. 又或者通过watch的方式, 也可以通过 b-linked="page.userList" 的方式, 这是变通的, 无需纠结. 

store与bui组件不搭是不准确的, 实际上是vue跟bui组件不搭,因为vue是用的虚拟dom, bui组件是真实dom, 所以才有bui.store 来解决这种数据双向绑定问题, 但是实际上bui的组件里面,已经有自己的实现方式, 无需使用 bui.store 来重新实现一遍. 目前 bui.store 我们自己推荐的场景就是在表单提交,表单展示方面, 筛选条件的处理,等等 数据的交互方式, 而不是操作的交互方式.
