### ISSUE TITLE
百度模板渲染问题

### ISSUE THREAD

**Issue by raisew** [imouou/BUI-Guide#11]
进入使用百度模板的页面后，需要刷新浏览器后html才有加进id容器里面，才有展示数据，我用的是你们的那套demo，请问这个问题要怎么处理哦？谢谢~

**Comment by imouou** [comment]
这个请查看是ID是不是重复冲突了, 所有页面的ID都不能一致, 如果一致, 请使用 router.$("id")[0] 模板那里需要以一个dom 对象传进去.

**Comment by raisew** [comment]
好的，明白
