### ISSUE TITLE
请求BUI的组件扩展教程

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#110]
作者，你好。

能不能出一个BUI组件的扩展教程，有的功能需要结合多个BUI的组件一起使用，例如弹出的打分(dialog+number)，在将它抽象为插件时只能使用jQuery的插件写法，特别希望能出一个组件扩展的教程，这样我们自定义的组件也能保持与BUI的组件一样的使用风格了。

以下是一个扩展示例：
```javascript
;(function($, bui, window){

    $.fn.score = function(options){
        options = options || {};
        return this.each(function(){
            options.appendTo = $(this);
            $.score(options);
        })
    }

    $.score = function(options){
        var opts = $.extend({}, defaults, options);
        // 1. create dialog
        var randomId = bui.guid();
        var uiDialog = bui.dialog({
            render: true,
            title: opts.title,
            content: `
                <div class="score-inner">
                    <div id="${randomId}" class="bui-number"></div>
                </div>
            `,
            buttons: [
                { name: '取消', value: 'cancel' },
                { name: '确定', value: 'confirm' }
            ]
        }).create({
            className: opts.className,
            appendTo: opts.appendTo
        });
        // 2. create score number
        var uiScoreNumber = bui.number({
            id: `#${randomId}`,
            min: opts.min,
            max: opts.max,
            step: 1,
            value: opts.value
        });
        // 3. bind
        uiDialog.selector().find('.bui-btn[value="confirm"]').one('click', function(){
            opts.onScore(uiScoreNumber.value());
        });
        // open
        uiDialog.open();
    }

    var defaults = {
        title: '打分',
        className: 'score-dialog',
        min: -10,
        max: 10,
        value: 0,
        appendTo: 'body',
        onScore: function(value){}
    };

})(jQuery || Zepto, bui, window);
```

**Comment by imouou** [comment]
(function(ui, $) {
    "use strict";;

    bui.extend({
        name: "score",
        config: {
            title: '打分',
            className: 'score-dialog',
            min: -10,
            max: 10,
            value: 0,
            appendTo: 'body',
            onScore: function(value){}
        },
        callback: function(opt) {

            // 拿到插件的公共方法
            let that = this;
            // 已经和参数合并过以后的
            let param = this.config;
            let randomId = bui.guid();
            let uiDialog = null;
            let uiScoreNumber = null;

            that.init = function(options){
                var opts = $.extend({}, param, options);
                // 1. create dialog

                uiDialog = bui.dialog({
                    render: true,
                    title: opts.title,
                    content: `
                        <div class="score-inner" style="height: 3rem">
                            <div id="${randomId}" class="bui-number"></div>
                        </div>
                    `,
                    buttons: [
                        { name: '取消', value: 'cancel' },
                        { name: '确定', value: 'confirm' }
                    ]
                }).create({
                    className: opts.className,
                    appendTo: opts.appendTo
                }).on("open",function(){
                    // 只初始化一次
                    if( uiScoreNumber ){
                        return;
                    }
                    // zepto 需要在打开以后才能初始化
                    // 2. create score number
                    // 动态dialog是创建在body下的, 控件的选择器都是相对路由的单页面, 所以这里需要使用 $选择器, 但是由于内部的选择器也都是相对于当前页的, 所以操作按钮会无效, 建议不使用动态创建的dialog, 自己自定义一个dialog模板, 然后初始化是 appendTo router.$(".bui-page") 这样控件就会正常的
                    uiScoreNumber = bui.number({
                        id: $(`#${randomId}`),
                        min: 0,
                        max: 5,
                        step: 1,
                        value: 3,
                        callback: function(e){
                            // opts.onScore(this.value());
                        }
                    });
                })
                
                // 建议方法可以在外部调用更加自由
                // uiDialog.open();

                return this;
            }
            that.open = function(){
                // open
                uiDialog && uiDialog.open();

                return this;
            }

            // 如果希望依赖被外部修改访问, 可以通过这种方式
            // that.widgets.loading = ui.loading({
            //     appendTo: opt.id
            // });

            // 会在父层的destroy方法触发前执行
            that.beforeDestroy = function() {
                // 如果有一些对象要释放,可以在这里写
            }

            // 是否允许初始化
            return that.init(opt);
        }
    });


})(window.bui || {}, window.libs);

**Comment by shoppingzh** [comment]
万分感谢！

**Comment by shoppingzh** [comment]
顺便问一个问题：如果使用者自定义组件，那么有的样式也需要自定义，为了防止组件名称或样式名在未来重复，应该遵循什么样的规则呢？

**Comment by imouou** [comment]
你命名的组件不要跟现有的官方组件冲突就行, 都是 .bui-xxx {}  .bui-xxx-main { } 这样的子集, 官方的组件如果再新增也会以扩展的方式提供了, 所以如果引入了两个不同的人做的类似的插件冲突的话, 那就看用哪个的问题.

**Comment by shoppingzh** [comment]
好的，理解了，谢谢您。
