### ISSUE TITLE
关于store组件的几点疑问

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#111]
作者，您好。
最近在使用store组件的过程中发现了一些问题，因为store使用到了Vue，于是学习了一些Vue的基础知识并与store进行比较，现将其记录如下：
1. **b-show只能在dispplay=block与display=none之间切换**，如果标签是span等内联标签，仍然会被设置为盒子模型，这很不利于对某些内联标签进行显示或隐藏。（Vue的v-show指令在处理span标签时，如果可见则会去掉display属性，如果不可见则设置为none，如果通过css将span置为display=block，那么在显示/隐藏间切换时，能保留用户之前设置的值）
2. **b-template在使用时只能传递一个参数**，如`<div b-template="page.tplList(page.list, page.type)">`这种方式只能获取到第一个参数的值，第二个参数获取不到，因为不懂这里面的原理，因此拜托解释一下，为什么模板不能同时对两个属性值进行监听？有时候模板的变化确实与多个值的变化相关
3. **b-template模板里如果也需要使用到如b-show这种语法好像是不行的**，但是可以使用b-model，同样请问这里面的原理是什么？这种场景其实也会经常出现，举例说：渲染一个用户列表，如果page.list有内容时则渲染出整个列表，反之则提示没有任何用户并提供`现在去添加`按钮，但是这个按钮的出现又与page.add属性有关，那么模板的定义可能就是这样(art-template)：
```html
  {{if list && list.length}}
    <li>...</li>
  {{else}}
    <p class="item-text">当前还没有用户哦！</p>
    <div class="bui-btn primary" b-show="page.add">现在去添加</div>
  {{/if}}
```
但是，目前这种写法，b-show是如法动态响应的。请问，如果碰到了这种问题时，如果解决比较好？
4. **store能不能提供Vue中v-if/v-for此类的语法？可否引入更多的Vue中的特性进来呢？**

目前就是这些问题，希望您能帮我解惑，谢谢！

**Comment by imouou** [comment]
首先很感谢你这么认真的在看以及使用, 这些建议对框架的改善都起到很大作用, 不过这里需要解释一个问题, bui.store 不是vue, 只是原理及API参考了vue的设计, 本质上两者的具体实现并不一致. 所以建议阅读的是 bui 的文档, 而不是vue的文档, bui.store 只是实现了vue很简单的一部分功能, 跟vue没法比. 

接下来解释下你的疑问: 
1. 你说的很有道理, 这个之前也已经考虑到了, 但是在新发布的版本并没有去实现, 即使是内联标签,也可能是block的样式, 目前常用的是整个块的隐藏, 到时新版会去修复这个问题;
2. 模板关注的是主要数据, 常见的就是列表, 这个列表的数据要跟模板绑定, 所以这里第一个数据是必须的, 第2个的数据完全可以在模板方法里面访问, 当时并没有加以考虑. 如果需要实现因为某个数据改变以后,关联模板变更, 那可以在watch里面监听实现关联. 
3. 你可能没有更新新版, 1.5.4 , 应该是支持的, 早期只支持 b-model 因为这个是通过事件监听, 所以不用关注数据渲染问题;
4. store 目前不会考虑模板语法, 这个在一开始就已经考虑去除这些if语法了, 很容易造成模板的维护问题, 就好像你一个数据的层级比较深, 你需要在模板里面写上 if list && list.data && list.data.length  等等, 这些并不利于维护. 相反使用 es6模板, 可以保持更加清晰的逻辑, 而模板跟逻辑是分开的. 当然如果你习惯, 你依然可以使用 art-template 之类的第三方模板引擎使用. 

bui.store 目前更多的就是用在一些表单场景, 还不适合用来做大型嵌套应用. 一切以简单为主.

**Comment by shoppingzh** [comment]
感谢作者开发了这么优秀的框架，我在学习与使用的过程中学习到了很多发现问题与解决问题的方法。学习Vue纯粹是希望从原理层面理解BUI的store组件，以免为一些细枝末节而困扰，也方我更直接地触达问题的根源，这是背景。

另外我还有几个问题：
1. 我现在在使用store来进行一些页面的表现控制，我试着让store来操纵整个页面的表现，在以前我只是拿它来做侧滑筛选（类似淘宝的过滤条件）功能，因为有的页面的表现受很多参数的影响，用js写起来很难控制边界条件，容易产生bug，因此才想到使用store来完成。请问，此一思路是否可行？（我还在坚持不懈地使用store组件，我相信它在未来有无限的可能性。）
2. 第二个问题是上次有个问题中提到了b-linked这个指令，但是最新的文档与API文档中好像都没有关于此指令的使用方法，由于也看不到BUI的源码，希望尽早将指令的使用方法补充到文档中。

**Comment by imouou** [comment]
bui.store 的原理后面有机会写写文章说明下. 
1. 可以用 bui.store 来设计整个页面的动态数据关联的交互, 比方模板,比方checkbox, 比方表单提交等, 只需要关注这些数据, 但我个人并不建议使用store来操作过多的页面交互, 页面交互尽量交由控件去实现, vue也好, bui.store 也好, 本质上操作的还是dom, 只是换了另外一个方式去实现. 
2. b-linked 这个是还没定的, 还没打算抛出来的, 所以并没有在文档出现, 这个也看后面使用的复杂度再看, 用起来会相对复杂一点

**Comment by shoppingzh** [comment]
嗯嗯，目前基本是按照您的这个思路实现的：
1. 使用store操纵的页面没有BUI的控件，如果有，将其分开处理，不使用store去操作BUI组件；
2. 页面中如果有用户交互的地方也基本上单独出来用jQuery来处理，使用store时往往是处理页面的表现而非交互。

还在继续摸索，学了一点Vue的基础，遇到问题还是使用Vue进行了一定的推理与思考，实在不懂还是要不断地麻烦您，当然有详细文档最好了。

**Comment by shoppingzh** [comment]
我使用的是npm上的最新的BUI的版本，在b-template的模板中使用了b-show指令，还是没有效果。请问能不能先发布一个稳定的1.5.4版本？（此外，在computed里监听数组长度失效的问题仍然存在）

**Comment by imouou** [comment]
buijs update 在项目执行更新命令

**Comment by shoppingzh** [comment]
抱歉，这个怎么操作？不懂。。。

**Comment by shoppingzh** [comment]
![image](https://user-images.githubusercontent.com/18109723/64411920-dce7fc80-d0c0-11e9-8584-898598d57cd6.png)

找到了，谢谢。

**Comment by shoppingzh** [comment]
另外，还有个问题，就是store在使用对象时，初始化的值可以是null，如：
```
data: {
     user: null
}
```
但是后续再对其进行修改的时候，不能再修改为null值了：
```
bs.user = null;
```
说一下应用场景：用户选择，选择了之后user不为空，点击删除后将user置为null，页面重绘。

另外，很遗憾的是我使用buijs更新版本后，之前的问题仍然没有得到解决，目前的问题：
1. b-show的问题
2. b-template中使用b指令的问题
3. 数组length探测问题
4. null值问题

**Comment by imouou** [comment]
这几个问题都在新版有解决的, 可以拿cdn 的测试版先用着, 多留意新版的发布.
