### ISSUE TITLE
actionsheet没有追加到页面上

### ISSUE THREAD

**Issue by hanle94** [imouou/BUI-Guide#114]
bui.ready(function() {
	var uiActionsheet = bui.actionsheet({
		trigger: "#btnOpen",
		buttons: [{
			name: "分享到微博",
			value: "weibo"
		}, {
			name: "分享到微信",
			value: "weixin"
		}, {
			name: "分享到QQ",
			value: "QQ"
		}],
		callback: todo,
		template: function(data) {

			var html = '';
			if (data && data.length) {
				// this.config.id 为对话框生成的唯一id
				html += '<div id="' + this.config.id + '" class="bui-actionsheet">';
				html += '    <ul class="bui-list">';
				html += '        <li class="bui-btn" value="按钮的值">按钮名</li>';
				html += '    </ul>';
				html += '    <div class="bui-btn" value="cancel">' + this.config.cancelText + '</div>';
				html += '</div>';
			}

			return html;
		}
	})

	function todo(e) {
		var val = $(e.target).attr("value");

		if (val == "cancel") {
			this.hide();
		}
	}

	uiActionsheet.show();

})
------------------------------------------
<script src="bui/js/zepto.js" type="text/javascript" charset="utf-8"></script>
	<script src="bui/js/bui.js" type="text/javascript" charset="utf-8"></script>
两个文件引用正常，
但是相关的html没有追加到页面上

**Comment by imouou** [comment]
你的dom 在哪, 你的BUI标准页面结构在哪? 可以按文档里面的来, 多看下示例的效果

**Comment by hanle94** [comment]
感谢指导☆⌒(*＾-゜)v，目前已经解决了，我有点菜 (⁄ ⁄•⁄ω⁄•⁄ ⁄)
