### ISSUE TITLE
模块化的一点疑问

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#115]
作者，你好，我又来了。

今天碰到一个问题，总结了一下原因，想跟您确认一下。
假设有一个`user.js`模块，在模块下的loaded回调里由于用户操作产生了一个数据a并将a存储于模块下：`this.a = 1`，只要我不同步刷新页面，重复进入到user模块下时，模块的a的值仍然没有发生变化。

我总结的原因是：
1. 页面第一次加载时初始化user模块，回调loaded，因为用户操作，产生了一个变量a=1
2. 页面第二次加载时由于user模块此前已经初始化，于是复用此模块，同样回调loaded，但是变量a与loaded是同一级的，于是a还是1
3. 因为模块并没有重复初始化，所以模块下的一些内部变量并不会清空

以上是我的一些思考，不知道对不对，希望您帮我解惑。另外有几个问题问一下，希望您抽空解答一下。

### 1. 组件的存储问题
我看到BUI的文档中也曾有过`this.uiInput = bui.input()`的写法，请问：
**组件的存储应该是交给模块呢，还是仅仅作为loaded回调里的局部变量就可以了？**

### 2. ajax懒加载的问题
私以为web app的开发最让人头疼的就是ajax的依赖与懒加载问题。依赖问题倒是不是那么棘手，原理就是从回调入手，如果B依赖A，那就让B的请求发生在A的回调里。如果有一个请求A，多处需要使用到它的成功回调这个也不是什么难题：
```javascript
var ajaxA = bui.ajax({
    url: 'getA'
});

function func1(){
    ajaxA.done(function(){
        // do sth
    })
}

function func2(){
    ajaxA.done(function(){
        // do sth
    })
}

```
虽然两处都使用到了A的结果，但是请求只发生了一次，这个也好理解。但是不好的事情是ajaxA这个请求会马上发生，但是实际情况是我们不可能把所有请求提前准备好，好比Tab页的懒加载一样，只有用户点击某个Tab时才加载页面内容，于是，我针对以上代码进行了改造，创造了一个ajax的**变量懒加载**，代码如下：
```javascript
var ajaxA;

function getA(callback){
    var get = ajaxA || (ajaxA = bui.ajax({
        url: 'getA'
    }));
    get.done(function(a){
        callback(a)
    }).fail(function(){
        alert('加载失败！')
    })
}
```
这是我想象出来的一种做法，原理还是基于回调，很好地解决了ajax的加载时机问题（谁先调谁先请求，此后调用不请求），为应用解决了资源。不知是否合理？特此想问一下：
**大前端下，怎么解决变量的懒加载问题？有没有成熟的解决方法？**

**Comment by imouou** [comment]
模块就是一个闭包，特性就是会缓存内部变量，所以模块的复用抛出来的应该是方法，动态获取这样才能在每个模块里面拿到正确的值，像A页面跳转到A页面，其实已经是两个不同页面了，只要里面有类似使用 router.$ 之类的选择器去选择做操作， 那操作的就是跳转后的页面，而不是上一个页面。store也一样，内部是有分页面去处理的，你A页面已经设置好值，那继续跳转页面，会重新执行一遍逻辑。

1. 组件的实例交给模块是为了给生命周期的其它时机调用， 正常不需要生命周期的话，使用变量存储就可以了。
2. 第一种方式就可以了，请求都是异步的，主要影响请求的是网络，而不是先请求后请求的问题，在你调用的时候能正确返回结果就行。
