### ISSUE TITLE
BUI中如何提取组件？

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#116]
作者，你好。

请问如何将一些通用的html块提取为组件使用？例如用户的简介信息可能会在多处用到，怎样才能写一处而多处使用？目前我的思路如下：
### 充分利用BUI的loadPart方法

可以将每个part视为一个组件，在part对应的模块中写组件的相关逻辑。

这里有个问题，loadPart的param参数是否是有长度的限制，是否可将一个很大的js对象传递到part中？我觉得是可以的，我推想loadPart的原理是使用jQuery/Zepto的load函数将html片段加载到某个容器内，然后require某个模块时再传递参数，所以此参数是直接传递的，并没有通过浏览器的地址栏进行解析。

在load时，一般情况下传递的都是基本数据类型，例如一个用户id，不建议直接将用户对象传递过去。这里还有个细节，在传递小对象时我会将对象序列化为json字符串传递，但是一般情况下不会传递大对象，因为要考虑到get请求URL的长度问题，如果序列化后的字符串长度太大，就可能导致数据丢失。

但是在loadPart时，一般情况下我们并不会直接传递id，而是传递对象，这在实际情况下是非常重要的，因为需要展示的数据在外层就已经查询好了，不需要在part模块中重复查询。这一点我是通过Vue的组件得到的启发，loadPart的param有点类似于Vue组件中的props，组件需要的往往是一个模型对象，不知这种理解是否正确？请指教。

**Comment by shoppingzh** [comment]
此外，还有一个问题，如何确定组件的html容器？使用router.$()的方式肯定会获取到路由页面的同id元素，这种情况如何处理？

**Comment by imouou** [comment]
对的，可以充分利用 loadPart，但如果只是模板，就没必要了，这个loadPart 是会跟load 一样，默认会执行一次脚本的，传参是跟 load 一样传一些简单的键值对，如果要传复杂的对象，就不应该这样传了。
```js
var param = {test:123}; //复杂对象
bui.loadPart({
id:"",
url:""
}).then(function(mod){
   mod.init(param)
})
```
另外，如果只是想共用模板，其实可以使用分开加载的方式，然后你想怎么传参都可以
```js
var param = {test:123}; //复杂对象
loader.import("url","id",function(){
    loader.require("",callback)
})
```

router.$ 获取到的是最后一个页面的选择器，最后一个页面本身就不应该出现相同ID的情况，应该是把页面的不同id, 传到模块里面去，这样模块的脚本通过id 做区分处理，模块才是真正的公共
