### ISSUE TITLE
bui.list如何拿到请求返回的json对象？

### ISSUE THREAD

**Issue by openpython** [imouou/BUI-Guide#117]
除了案例中的 template: function (data) {...} 没看到有拿到返回对象的方法呢

**Comment by imouou** [comment]
onLoad，
onRefresh 都可以拿到每次请求以后返回的数据， 可以先了解下控件的API

**Comment by openpython** [comment]
bui.list API没找到调用返回数据的代码，只看到这样的案例
 onLoad: function() {
            // 刷新以后执行
            console.log("loaded")
}

请问调用返回数据具体名字是什么？因为返回的数据除了构造template，还有些附加数据，不知道怎么获取到名字

**Comment by imouou** [comment]
onLoad: function(res) {
// 刷新以后执行
console.log(res)
}

**Comment by openpython** [comment]
有点糊涂。。。这个对象打印了，没找到服务器返回的数据。
![222222](https://user-images.githubusercontent.com/1044542/65560959-44cc8d00-df73-11e9-8315-b279a28fcc67.jpg)

**服务器返回的**
![vvvvv](https://user-images.githubusercontent.com/1044542/65560963-50b84f00-df73-11e9-98ea-5486294c7a6f.jpg)

**Comment by imouou** [comment]
function (mod,result) {
    第一个是只是旧版的 this, 兼容问题所以没改，都在第2个参数是返回的所有数据
}

**Comment by openpython** [comment]
拿到了，谢谢
