### ISSUE TITLE
tab选项卡配合bui.list控件有冲突

### ISSUE THREAD

**Issue by openpython** [imouou/BUI-Guide#118]
list控件左右滑动超出了屏幕，横向无限滑动。而且触发了tab的onBeforeTo事件。
![111](https://user-images.githubusercontent.com/1044542/65521197-6c900680-df1b-11e9-9402-0473220021d2.gif)

**Comment by openpython** [comment]
![bbbb](https://user-images.githubusercontent.com/1044542/65562011-2f596200-df77-11e9-8d07-130f8f73b2b5.jpg)
换了简单的代码测试了下，在tab内容项的滑动都会引发tab nav的onBeforeTo事件。这个设计是不是有点问题。内容项引发onBeforeTo事件却无法获取到tab索引数据了。

**Comment by imouou** [comment]
是的，有这样的情况，是在什么情况下需要用到这个回调呢？

**Comment by openpython** [comment]
场景就是有多个tab项，点击每个tab项获取项的data-<参数>来请求服务器数据，初始化对应的uilist。
`<div id="uiNavbar" class="bui-navbar">
            <ul id="nav" class="bui-nav"><li class="bui-btn" data-symbol="btc" data-index="0">BTC</li><li class="bui-btn" data-symbol="ltc" data-index="1">LTC</li><li class="bui-btn" data-symbol="eth" data-index="2">ETH</li><li class="bui-btn" data-symbol="bch" data-index="3">BCH</li></ul>
        </div>
        <div id="uiTabNavbar" class="bui-tab">
            <div class="bui-tab-main">
                <ul>
                    
                    <li></li>...
</ul></div>
        </div>`

`var uiTab = bui.tab({
    	id:"#uiTabNavbar",
    	menu:"#nav",
    	onBeforeTo: function(e) {
    		console.log(e.target);
    		var symbol=$(e.target).data('symbol');
    		var curIndex = parseInt($(e.target).data('index'));
    		initUiList(symbol, curIndex);
    	}
    });`

**Comment by imouou** [comment]
uiTab.on("to",function(index){
       console.log(index) 
       在跳转后每次获取菜单的第几个去使用
})

**Comment by openpython** [comment]
这样可以的，解决了
