### ISSUE TITLE
RequireJs的使用疑问

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#119]
作者，你好。最近在使用BUI的过程中有一些心得体会，以下陈述一下个人的拙见，望作者予以置评。

### 背景
前后端分离后，大量的代码挪动到了前端，每个页面的业务代码其实被封装到了一个一个的js模块中，这样可以很好地隔离每个页面的数据，同时可以将模块的接口抛出。但是，除了这些页面外，其实还有很多的其它的操作如图片的压缩、解析，表单的校验、app的数据维护等，如果不将它们封装到模块中，那么就容易污染整个全局变量的空间，于是，我将它们也抽象为了一个一个的模块。

### 实践
以操作图片的工具为例，我在项目的js/modules目录下定义了一个imageKit模块，内容如下：
```javascript
loader.define(function(require,exports,module){

    /**
     * 等待图片加载完成
     * 当图片被缓存时仍然能回调
     * @param {String} src 图片源地址
     * @param {Function} callback 回调
     */
    function waitImageLoaded(src, callback){
        var img = new Image();
        img.src = src;
        if(img.complete){
            doCallback();
        }else{
            img.onload = function(){
                doCallback();
            }
        }

        function doCallback(){
            if(callback && typeof callback === 'function'){
                callback(img.width, img.height);
            }
        }
    }

    /**
     * 将图片文件读取为base64编码的字符串
     * @param {File} file 图片文件
     * @param {Function} callback 回调
     */
    function readFileAsBase64(file, callback){
        if(!file){ return ; }
        var fr = new FileReader();
        fr.readAsDataURL(file);
        fr.onload = function(){
            if(callback && typeof callback === 'function'){
                callback(fr.result);
            }
        }
    }

    return {
        waitImageLoaded: waitImageLoaded,
        readFileAsBase64: readFileAsBase64
    };
})
```

私以为，这样做的好处是：
1. 将函数很好地进行分类，例如表单校验可以定义一个validator模块，这样模块抛出的接口命名不再像定义一个全局函数那样需要小心翼翼防止重名冲突等问题
2. 模块内部还可能有它的内部数据，如果定义全局函数，那么这些数据就只能位于全局作用域下，这样又污染了全局作用域了
3. 使用时可以按需加载，例如某个页面需要读取图片的base64编码值，那么只需要像下面这样调用：
```javascript
loader.require(['js/modules/imageKit'], function(kit){
    kit.readFileAsBase64(file, function(base64){
        // ...
    });
});
```

### 问题
1. 最近狂补了一些前端模块化的知识（我是后端工程师），我的感觉是模块化其实就是闭包的一个封装，模块抛出的是接口，它既可以抛出数据，也可以抛出方法，同时，它也有一些无法被外部进行访问的内部数据。在使用时，它更像使用其他语言一样，可以随时import其他模块并使用。因此，私以为应该将模块化的思想大量地应用到我们的项目，它可以让我们的项目代码变得更加清晰和统一。不知道这种想法是否在BUI的工程里值得推广，请作者给点指示。
2. BUI的模块加载貌似都是CMD的形式？require支持同步加载吗？有时候我想这样调用：
```javascript
var kit = require('js/modules/imageKit');
kit.readFileAsBase64();
```
这样写代码更优美，而不用一个函数套一个函数，如果同时依赖多个模块就会发生嵌套很多层回调函数的情况，请问此类问题如何解决？
3. 另外，loader.define()的depend参数好像也是异步加载的吧？我如何拿到这些依赖的抛出啊？如：
```javascript
loader.define({
    depend: ['js/modules/imageKit'],
    loaded: function(r, e, m){
        // 在这里如何拿到imageKit模块？
    }
});
```

**Comment by imouou** [comment]
1. 对的，模块里面就是一个闭包，抽象出项目中跟通用模块可以用于多个项目，BUI本身也是推荐这种模块化组织方式的，但就不建议层级太深，比方 A依赖B，B依赖C，C又依赖于D， 还要避免模块的嵌套循环；
2. BUI的模块是AMD的，类似requirejs 的使用，目前不支持CMD的方式；
3. seajs 推崇的是依赖就近，也就是第2种的使用，BUI里面跟requirejs推崇的是 依赖前置。
```js
loader.define({
    depend: ['js/modules/imageKit'],
    loaded: function(imageKit, r, e, m){
        console.log(imageKit) 其它会往后
        // 在这里如何拿到imageKit模块？
    }
});
```
