### ISSUE TITLE
关于bui dialog 点击确定按钮自动关闭的问题

### ISSUE THREAD

**Issue by smdbs2000** [imouou/BUI-Guide#120]
我定义了一个在屏幕中间打开的弹窗，如何做才能使得在点击“确定”按钮或者“取消”按钮的时候，不会自动关闭呢？下面是我根据demo做的dialog底部的代码。
`<div class="bui-dialog-foot">
      <div class="bui-box">
        <div class="span1">
          <div class="bui-btn cancel-btn">取消</div>
        </div>
        <div class="span1">
          <div class="bui-btn blue submit-btn">确定</div>
        </div>
      </div>
    </div>`

**Comment by imouou** [comment]
初始化 dialog 的时候，把 autoClose 参数设置为 false , 这些基本使用可以优先查阅 API

**Comment by smdbs2000** [comment]
收到，是我没有仔细阅读API，以后我会更加仔细的去查阅API。非常感谢你的及时回复。

> 初始化 dialog 的时候，把 autoClose 参数设置为 false , 这些基本使用可以优先查阅 API
