### ISSUE TITLE
关于upload组件添加文件时，出现相同index的问题

### ISSUE THREAD

**Issue by smdbs2000** [imouou/BUI-Guide#123]
我在使用官网的文件上传demo时，发现一个问题，例如我添加了3个文件，文件的index分别为0、1、2，但当我删除掉index为0的文件，再添加一个新的文件时，发现新添加的文件的index还是2，而不是3。这样会导致在逐个删除文件时，index为2的文件删除时js会报错，无法删掉。请问这个问题该怎么解决呢？另：该问题还会导致上传到服务器的文件中，index为2会重复上传一次，而index本该为3的文件却没有上传至服务器。
页面生成的代码如下（由于图片的base64值太长，在此省略）：
`<div id="facePhoto" class="bui-upload bui-fluid-space-4">
          <div class="span1" data-index="1" data-name="undefined">
                <div class="bui-upload-thumbnail"><img src="data:image/png;base64," alt=""><i class="icon-removefill"></i></div>
                </div><div class="span1" data-index="2" data-name="undefined">
                <div class="bui-upload-thumbnail"><img src="data:image/png;base64," alt=""><i class="icon-removefill"></i></div>
                </div><div class="span1" data-index="2" data-name="undefined">
                <div class="bui-upload-thumbnail"><img src="data:image/png;base64," alt=""><i class="icon-removefill"></i></div>
                </div><div class="span1">
            <div class="bui-btn" id="qst-btnUpload">
              <i class="icon-plus large"></i>
            </div>
          </div>
        </div>`

**Comment by imouou** [comment]
有看到了, 等修正

**Comment by smdbs2000** [comment]
> 有看到了, 等修正

收到，我目前的解决办法是使用start进行上传，避免使用startAll。
删除的时候，只删除页面内容，不在js中执行uiUpload.remove(index)。

**Comment by imouou** [comment]
这个remove 其实可以支持名称, 只是现在拿到的名称是不正确的, 正常通过名称去删除就可以了, 先这样把, 后面更新例子, 但我们更建议点一次上传一张, 返回远程图片做展示, 这样可以避免很多问题.
