### ISSUE TITLE
upload 组件如何批量上传完毕再执行ajax提交表单，start方法上传使用二进制文件上传

### ISSUE THREAD

**Issue by Iamasdf** [imouou/BUI-Guide#125]
现在使用bui.upload遇到一个问题是，我想用户添加完全部图片后，点击提交按钮，使用startAll方法先上传图片，然后根据上传结果全部成功后再异步执行ajax表单提交文本内容。
这个方法是每个图片都执行一次ajax上传请求，中间有上传失败在onFail 失败回调 .stop() 和 return false;都没有总之上传，全部图片继续执行上传，而且 后面的ajax表单提交也执行了。
ajax表单提交是写在 startAll()方法下面，有没有什么可以知道上传状态是不是全部上传完毕。我在 onSuccess 也可以判断完毕后在执行 ajax上传表单。

另外是使用start方法,我想换成startAll的二进制方式上传应该怎么配置 。调用data()的数据是一个对象，

`uiUpload.start({
                url: "url",
                fileKey:'image',
                data:{file: uiUpload.data()},
                onSuccess: function (res) {
                    // 成功
                    upladAllStatus=true;
                },
                onFail: function (res,status) {
                    // 失败 status = "timeout" || "error" || "abort", "parsererror"
                }
            })
`
提交后后端接受到是一个image 字段下base64内容和file 是 [object Object],[object Object] 的文本内容。

**Comment by imouou** [comment]
这个上传是为了统一web以及原生的方式, 如果需要更复杂需求的上传图片, 可以采用第三方的上传. 

单个上传,默认会上传最后一个选择的图片, 你也可以指定第几个文件. 

uiUpload.start({ url: "url", fileKey:'image', data:{file: uiUpload.data()[0]["data"]}, onSuccess: function (res) { // 成功 upladAllStatus=true; }, onFail: function (res,status) { // 失败 status = "timeout" || "error" || "abort", "parsererror" } })
