### ISSUE TITLE
导航栏会出现报错现象

### ISSUE THREAD

**Issue by Iamasdf** [imouou/BUI-Guide#126]
http://www.easybui.com/demo/#pages/ui_controls/bui.tab_head_dynamic

下载demo的多页面实例在，bui内核报错误。

 Cannot read property 'getLast' of undefined:TypeError&&stack:TypeError: Cannot read property 'getLast' of undefined   bui.js:7

> var tab = bui.tab({
        id: "#tabDynamic",
        // 1: 声明是动态加载的tab
        autoload: true,
    })
    
初始化 autoload:false 就开始报错

loader.require 也不能使用

如果换成 tab.load 方法，点击tab显示的是下一个tab的链接的内容，会出现错位

**Comment by imouou** [comment]
查看源码仅供学习使用, 实际里面项目还需要异步加载其它不同模块, 可以把整个控件示例拿下来, 查看对应的加载就行. 默认都是单页模块

**Comment by Iamasdf** [comment]
是单页面的，点击是源码那个多页面，下载下来是单个html的已载入需要的类库，是个完整的demo，但是打开初始化就报错 

Cannot read property 'getLast' of undefined:TypeError&&stack:TypeError: Cannot read property 'getLast' of undefined   bui:7

Uncaught TypeError: Cannot read property 'getLast' of undefined  bui:9

更换过浏览器也是这样 

loader.require() 应该不用另外再加载其他组件 就可以使用，依照文档那样的例子 
http://www.easybui.com/demo/index.html#pages/ui_loader/require
loader.require(["pages/page2/page2"],function(page2){
    // page2 == {page:"page2"} 
})
用到这个方法就会报错

**Comment by imouou** [comment]
最新版本已经修复 https://cdn.jsdelivr.net/npm/buijs@1.5.50/lib/latest/bui.js

**Comment by Iamasdf** [comment]
测试了新的版本，没有报错，但是有个新的问题出现 loader.require(["pages/ui_controls/bui.tab_dynamic_page1.html"])  
使用loader.require 方法 自动会在后缀加上.js  变成了 /pages/ui_controls/bui.tab_dynamic_page1.html.js

**Comment by imouou** [comment]
> 测试了新的版本，没有报错，但是有个新的问题出现 loader.require(["pages/ui_controls/bui.tab_dynamic_page1.html"])
> 使用loader.require 方法 自动会在后缀加上.js 变成了 /pages/ui_controls/bui.tab_dynamic_page1.html.js

loader.require 本来就是用来加载脚本, 要加载静态HTML 可以使用 loader.import , 之间不一样
