### ISSUE TITLE
upload组件问题

### ISSUE THREAD

**Issue by FFCZ** [imouou/BUI-Guide#127]
v1.5.4，添加若干图片，可以正常预览，按顺序从右到左删除，没问题，随机不按顺序删的话，就会出现不能删除问题。提示是  Cannot read property 'name' of undefined
同样，currentName方法会出现undefined，官方demo同样问题。

**Comment by imouou** [comment]
这个最新版本已经修复了, https://cdn.jsdelivr.net/npm/buijs@1.5.50/lib/latest/bui.js

**Comment by FFCZ** [comment]
> 这个最新版本已经修复了, https://cdn.jsdelivr.net/npm/buijs@1.5.50/lib/latest/bui.js

感谢你的回复。刚更新了版本，currentName可以正常获取到文件名。
但是，Cannot read property 'name' of undefined，这个问题还在存在。
操作如下，使用官方demo程序：
1、添加A B C D四张图片，base64形式预览
2、按顺序删除，icon-removefill 事件，D C B A顺序逐个删除，没问题。
3、按ABCD 顺序删除，就会提示name undefined。
4、按CBAD随机删除，会有同样提示。
chrome78调试

**Comment by imouou** [comment]
示例没有更新, 你可以试试最新的demo
