### ISSUE TITLE
表单元素设计不符合可接入准则

### ISSUE THREAD

**Issue by arm-liang** [imouou/BUI-Guide#128]
除了基本表单项之外的其他高级功能组件都不是使用 表单元素实现的
大量点击按钮使用 div span 替代
网页可接入性不好
比如 bui.select 就可以通过一个隐藏的select来保存数据，但是事实是在span1里面添加 name text value属性
而且大量使用div span 替代原生表单元素 获取表单数据和进行表单验证也是一件麻烦的事情，官网我现在还没有找到统一的解决方案来处理表单验证和表单数据获取提交

**Comment by imouou** [comment]
bui的控件支持静态绑定及动态绑定两种方式, 如果通过隐藏域的方式, 用户难免有遗漏, 这也是当初没有采用的原因之一, 第2个原因, 数据动态弹窗出来的元素,并不在你的表单标签内, 也就你的数据一样会有遗漏. 其实移动端的开发跟PC开发不太一样, 只需要关注要提交的数据就行, 具体可以查看 bui.store 的表单那边的用法, 一个展示,一个提交, 你都可以操作同一个数据, 做好对应的关联就行.

**Comment by arm-liang** [comment]
由于工作原因非常抱歉这么晚才回复
我提到的使用静态域保存表单数据是类似layui这种的
![image](https://user-images.githubusercontent.com/37470680/69024387-7d319a00-09fd-11ea-955f-778c1f969b4b.png)
隐藏原生表单元素使用div展示
在提一点小问题：
官网的文本输入框和文本内容展示框能否做到一块，文本展示框如果需要编辑的话就需要额外操作dom
希望能提供静态绑定方式的表单数据统一获取

**Comment by imouou** [comment]
不同的实现方式, 那种是pc的处理, 跟我们的处理方案是不一致的, 可以查看 http://www.easybui.com/demo/#pages/store/input  当你把数据相关联以后, 没有那么复杂.

**Comment by arm-liang** [comment]
- 果然数据动态绑定才是潮流🤔
动态数据绑定的话还是可以考虑的
- 如果能语义化标签就好了
button.bui-btn标签 比后面的好 div.bui-btn li.bui-btn
