### ISSUE TITLE
fixStatusBar.js 问题

### ISSUE THREAD

**Issue by raisew** [imouou/BUI-Guide#13]
fixStatusBar.js 这个js怎么使用，有没有文档说明哦？

**Comment by raisew** [comment]
用Apicloud打包，顶部应该怎么处理哦

**Comment by weiwuying123** [comment]
apicloud引入fixStatusBar.js后footer被挤到屏幕下方了是咋回事呀？

**Comment by imouou** [comment]
> apicloud引入fixStatusBar.js后footer被挤到屏幕下方了是咋回事呀？

这个fixStatusBar 的用处是针对IOS打包全屏, 特别是iphonex 的问题才会有的, 这个根据自己需求再看是否引入就好.
