### ISSUE TITLE
页面通过depend依赖其他模块的问题

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#130]
作者，你好。

最近我发现这么一个问题：当我在某个页面模块中前置依赖其他的模块时，第一次进入时会导致当前模块的`loaded`无法回调，然后再次进入就好了，请问这是怎么回事？可以解决吗？目前这种问题可能会很困扰用户。

![image](https://user-images.githubusercontent.com/18109723/69686269-3bd67400-10fa-11ea-8c3f-8b868953d7d0.png)

![image](https://user-images.githubusercontent.com/18109723/69686282-4a249000-10fa-11ea-9a4d-07f3061c6531.png)

可以看到，加载到最后一个依赖的模块后并没有发生ajax请求，页面也没有渲染，说明`loaded`没有回调。

**Comment by imouou** [comment]
cdn 的beta版有修复了, 拿最新的版本下来使用 https://cdn.jsdelivr.net/npm/buijs/lib/latest/bui.js  20191123 的版本

**Comment by shoppingzh** [comment]
好的，谢谢
