### ISSUE TITLE
#Form表单的数据如果获取？

### ISSUE THREAD

**Issue by matols** [imouou/BUI-Guide#131]
整个表单的数据如何获取呢？
正常的input标签问题不大，主要是div的下拉选项怎么办？

**Comment by imouou** [comment]
正常不使用pc的方式, 如果要用, 那就使用隐藏域, 你可以给下拉选项框的 onchange 事件, 把值存在 隐藏域, 然后提交. 如果需要双向绑定, 使用 bui.store 把数据跟控件进行关联, 提交对应的字段就行

**Comment by matols** [comment]
感谢解答！
其它，可以尽量使用原生的HTML标签组的，或封装。这样BUI就可以移动端、PC端通用了。

还有一个建议，就是目前的BUI在进行表单的数据处理上，是不是可以兼容一下PC的数据封装？比如常见的表单验证、表单提交等。

也许你们专业的前端工程师，都是使用诸如数据驱动的双向关联方式，但还是有大量的PC表单时代的用户存在的。

**Comment by matols** [comment]
更加HTML原生化，哈哈
