### ISSUE TITLE
手机物理返回键，APP直接退出问题？

### ISSUE THREAD

**Issue by matols** [imouou/BUI-Guide#132]
是使用过程中，通过Header里的返回按钮，操作一切正常！

但是，使用手机的物理返回键后，APP立马退出。不知道手机物理返回有什么需要特殊处理吗？

**Comment by imouou** [comment]
这个手机物理设备需要用到原生能力,可以参考对应的打包平台的使用. 也可以使用bui做好的工程去处理.
比方dcloud平台,  使用命令创建 `buijs create -p dcloud` 这样工程的 index.js 有个注释, 打包的时候去掉就可以了, 另外这样创建的工程 bui.js 是不一样的, 需要替换自己工程的脚本.

**Comment by matols** [comment]
感谢回复。
只需要加上这个Dcloud平台的原生兼容函数就行了吗？

// 绑定物理后退按键
bindBack();
