### ISSUE TITLE
轻应用本地调试的时候使用bui.ajax 不能正常请求，使用app.ajax可以正常请求，导致了bui.list不能正常使用，请问有解决办法吗

### ISSUE THREAD

**Issue by MarkGaozhq** [imouou/BUI-Guide#133]
bui.ajax({
        url: "http://www.easybui.com/demo/json/shop.json",
        data: {
            pageindex: 1,
            pagesize: 10
        }
    }).done(function(res) {

        // //生成html
        // var html = template(res.data);

        // $("#scrollList")[command](html);

        // // 更新分页信息,如果高度不足会自动请求下一页
        // _self.updatePage(page, res.data);

        // // 刷新的时候返回位置
        // _self.reverse();
    }).fail(function(res) {
        // console.log("res");
        // console.log(res); 
        // // 可以点击重新加载
        // _self.fail(page, pagesize, res);
    })
}
![1575429174(1)](https://user-images.githubusercontent.com/16422653/70109546-30012980-1687-11ea-9cf6-6a640581679b.jpg)
![1575429185(1)](https://user-images.githubusercontent.com/16422653/70109570-40190900-1687-11ea-825c-9f0c044bed7a.jpg)

**Comment by imouou** [comment]
轻应用本地打包的没有跨域问题, 远程调试需要切换成原生处理, 查看你的 bui.js 的平台是什么平台, 版本号多少, 另外如果是内部同事, 请进内部交流群.

**Comment by MarkGaozhq** [comment]
具体怎么操作啊，项目中第一次使用bui框架，有内部Link群吗?

**Comment by MarkGaozhq** [comment]
![1575430304(1)](https://user-images.githubusercontent.com/16422653/70110355-abfc7100-1689-11ea-8fcf-defe5459d0ef.jpg)

**Comment by MarkGaozhq** [comment]
轻应用打包后已正常
