### ISSUE TITLE
文档都翻烂了，也没找到哪里说可以加载外网网页？

### ISSUE THREAD

**Issue by matols** [imouou/BUI-Guide#134]
不知道除了路由加载项目内的地址跳转以外，能加载公网的url地址吗？

**Comment by imouou** [comment]
本身就是一个webview, 用window.location.href = "xxx" 就可以跳转.  如果想保留原有的路由动画, 则需要使用 bui.load({url:"",iframe:true});    这些在路由的demo都有例子. 

http://www.easybui.com/demo/#pages/router/index

**Comment by matols** [comment]
多谢，我以为 bui.load 只支持内部页面
