### ISSUE TITLE
如何使bui兼容IE11

### ISSUE THREAD

**Issue by smdbs2000** [imouou/BUI-Guide#135]
用IE11打开bui开发的web程序是白屏的，没有任何显示，控制台也没有报错，不知道该如何解决。服务器用的是tomcat8.5。

**Comment by imouou** [comment]
bui是一个移动App开发框架, 不是PC Web程序, 不支持IE, 仅支持 Chrome, Safari 等 webkit 内核.

**Comment by smdbs2000** [comment]
明白了，谢谢回复。
