### ISSUE TITLE
bui.ajax如何上传文件？

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#136]
作者，你好。

bui.ajax如何才能上传文件？我使用FormData上传不了，然后看文档说明了data字段只能是json格式？

使用bui.ajax不行，转而我就想使用$.ajax的方式上传，发现还是不行，content-type头都没有了！我怀疑是bui的初始化修改了jQuery的ajax全局配置，于是我在bui初始化之前发起了一个使用FormData的ajax请求，一切正常，content-type请求头为`multipart/form-data`。

我知道另一种解决方案，但是这个方案并不太好，就是使用bui.upload，然后把普通表单字段封装在data字段里，这个方法有个致命的弱点就是只支持单文件的上传，如果在一个表单中有两个不同参数名的文件需要上传，那该怎么办呢？

所以，现在我是用$.ajax、bui.ajax、bui.upload都完成不了这个表单的提交，请问作者，此问题该如何解决？

**Comment by imouou** [comment]
$.ajax 没有修改的, bui.ajax 本质上就是 $.ajax , 只要 $.ajax 可以, bui.ajax 就可以.  另外针对上传文件, 最好的办法就是使用bui.upload,  只需要初始化一个, 调用 upload.start 方法你可以任意把文件传过去, 而不是等最后表单提交的时候, 再一块传.
