### ISSUE TITLE
整合video.js框架时的问题

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#139]
作者，你好。

我在项目中引入了video.js框架来播放视频，但是引入该框架后发生了一些奇怪现象，视频层的控制栏的每个按钮，事件被绑定了两次（估计应该是事件重复绑定的问题），导致每次在播放状态点击暂停时失效（经历了暂停 -> 播放两个状态），如果我把同样的代码移出BUI项目，则问题不重现，请问这个问题的原因是什么以及怎么解决？

播放器初始化代码：
```javascript
$page.find('video').each(function(){
    var player = videojs(this, {
        language: 'zh-CN',
        controls: true,
        autoplay: false,                   // 不自动播放
        preload: true,
        fluid: true,                       // 宽高自适应
        controlBar: {
            pictureInPictureToggle: false, // 关闭画中画
            fullscreenToggle: false        // 关闭全屏
        }
    });
})
```

问题截图：

![GIF](https://user-images.githubusercontent.com/18109723/71075383-ec4a0c00-21be-11ea-98f8-c20d9dee9f38.gif)

**Comment by shoppingzh** [comment]
请问作者，您有看到吗？麻烦回复一下

**Comment by imouou** [comment]
这个跟bui没有关系的, 你的视频初始化在一个循环里面, 如果页面有多个video自然就会绑定多次. bui不会去绑定videojs 的东西.

**Comment by shoppingzh** [comment]
我单独跑了一个最小的bui例程，使用了一个确定的video元素，仍然发生了这样的情况。

但是同样的例程抛在非bui环境下，就没有任何问题。

请问，如何思考和解决这个问题呢？

**Comment by imouou** [comment]
官方例子并无这个问题 http://www.easybui.com/demo/#pages/thirdpart/videojs/index

**Comment by shoppingzh** [comment]
感谢！我这边已经测试出了结果，是百度touch库与videojs库之间的不兼容问题
