### ISSUE TITLE
Apicloud 打包编译问题

### ISSUE THREAD

**Issue by raisew** [imouou/BUI-Guide#14]
用apicloud编译测试包下载后打开，提示： bui.loader.execute Cannot read property 'open' of undefined: TypeError&&stack:TypeError: Cannot read property 'open'of undefined at Object.e.init(file:///android_asset/widget/dist/pages/main/main.js:1:196) 等... 能帮忙看下 是哪里没处理好吗

**Comment by imouou** [comment]
buijs create -p apicloud 这样创建的工程, 执行npm run build 生成的dist 目录, 复制里面的内容, 去覆盖 apicloud 新建的工程, 这样创建的工程可以绑定手机后退等处理
