### ISSUE TITLE
页面传参在新页面获取参数并初始化时ajax请求时出现异常

### ISSUE THREAD

**Issue by liuzhl** [imouou/BUI-Guide#140]
pageview.init = function () {
        //获取参数
        var params = router.getPageParams();
        var id = params.id;
        bui.get("apps/mchnt/getInfo",{id:id},[{needNative:true}]).then(function(res){
            console.log(res)；
          })
        // 绑定事件
        this.bind();
    }

出现异常信息：Uncaught ReferenceError: plus is not defined
![image](https://user-images.githubusercontent.com/41617442/71438861-52d8a800-2732-11ea-894a-266bbefa89a9.png)

**Comment by imouou** [comment]
查看下你的 bui.isWebapp 有没有等于 true;  bui.config.ajax = { needNative:false }  ;  如果needNative:true 不能在PC调试

**Comment by liuzhl** [comment]
没有设置 bui.isWebapp，因为之前的接口都是bui.get("url",{id:id},[{needNative:true}])这种形式调用，是可以在PC上调试的，唯独页面跳转根据参数http请求出现异常，去掉[{needNative:true}]的确是没有问题。
