### ISSUE TITLE
单页模式，tab中加载模块后无法渲染bui.list

### ISSUE THREAD

**Issue by fanxin4576** [imouou/BUI-Guide#141]
在单页模式里，loader.require(["pages/main/topic"])后，bui.list的template已经正常返回，但列表没有渲染出来

**Comment by imouou** [comment]
bui.list 重点理解 field 字段映射的概念, 查看API的文档, 有举例子说明你的数据及field 应该怎么配置.

**Comment by fanxin4576** [comment]
答非所问啊，大哥

**Comment by fanxin4576** [comment]
> bui.list 重点理解 field 字段映射的概念, 查看API的文档, 有举例子说明你的数据及field 应该怎么配置.

答非所问啊，大哥

**Comment by imouou** [comment]
列表没有渲染出来要看下有没有进入到列表模块里面
