### ISSUE TITLE
depend其它模块的另一个问题

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#142]
你好，作者。

还是依赖模块的一个问题，如果我修改了页面js的源码，在下次进入页面时，会导致页面无法渲染（实际上只加载了依赖的前几个模块，后面的依赖由于没有加载，所以进入loaded回调失败）

请问该问题的出现原因是什么以及如何解决？

**Comment by imouou** [comment]
不理解, 是否跟前面的页面有一样的模块依赖, 是的话, 试试把已经加载过的依赖, 放在依赖前面, 不放在最后.

**Comment by shoppingzh** [comment]
我试了一下，确实好像解决了问题。

另外重新描述一下我的问题，假设A页面：
```js
depend: [ 'module/x', 'module/y'  ]
```

B页面：
```js
depend: [ 'module/z', 'module/x', 'module/y' ]
```

页面从A路由到B，此时B页面在第一次进入时执行`module/z`的加载，但是进入不到`loaded`回调中。

**Comment by imouou** [comment]
嗯, 这个后面1.5.6新版会解决这个问题的, 现在使用尽量避免把加载过的放最后, 全加载过以及全未加载都没问题.

**Comment by shoppingzh** [comment]
嗯嗯，好的，谢谢
