### ISSUE TITLE
在引用的第三方js回调函数里，进行初始化后的对象如何使用？

### ISSUE THREAD

**Issue by matols** [imouou/BUI-Guide#143]
loader.import("js/f2-all.min.js",function(){ 
       const chart3 = new F2.Chart({
		id: 'mt3',
		pixelRatio: window.devicePixelRatio
	});
}); 
loader.define(function(){
    var pageview = {};
    pageview.init = function () {
         //如果使用引入的三方资源回调后初始化完成的对象呢？
         chart3.render();
    }

    pageview.init();
    return pageview;
})

在引用了第三方js加载后，会进行一些初始化的工作，比如初始化图表对象。
可是如果我在pageview.init(); 里想要使用这个对象，该如何处理呢？

这里影响的因素包括，import资源和当前define的加载顺序？执行顺序导致的访问域问题？

还请赐教！谢谢！

**Comment by imouou** [comment]
这个结构本身就是错的, loader.import 应该在 loader.define 里面, 这样就可以把 chart3 定义在外层, 作为整个模块的局部变量, 那样初始化一次以后就可以拿到对应的图表实例了.

**Comment by matols** [comment]
原来是这样啊！我去试试，感谢！
