### ISSUE TITLE
ios真机运行和打包(dcloud)出现白屏，Android正常。

### ISSUE THREAD

**Issue by southmaple** [imouou/BUI-Guide#145]
单页面项目修改了一些功能后，重新打包后发现android正常使用。ios启出现动图后就白屏（很多ios都一样），没语法报错，然后就下载最新的单页开发包直接打包和真机运行也出现类似情况。后面对代码整理发现只要初始化路由就会出现白屏。

**Comment by imouou** [comment]
如果是Dcloud平台, 去该平台搜索有对应的解决方案. IOS 自己打包需要解决本地文件的跨域安全问题.

**Comment by southmaple** [comment]
2月之前还正常，现在就不行了。我去找找看

**Comment by imouou** [comment]
这个问题dcloud新版IOS打包默认使用 wkwebview 安全更高,所以不能使用跨域了,BUI 新版打包的时候IOS可以切换一个状态, 使用原生去请求.

**Comment by matols** [comment]
我今天打包到ios也是这样的，安卓一切正常，ios加载完启动图片后，立马白屏，不知道咋办？

**Comment by imouou** [comment]
IOS现在只能wkwebviw, wkwebview本地文件存在请求跨域问题, 这个dcloud的平台的原生请求不支持本地文件跨域, 可以更新新版的 dcloud 版 bui.js, 在index.js `bui.ready` 前面加上下面的代码. 

// 安卓无跨域问题, 默认bui.ajax 就可以
if( bui.platform.isIos() ){
    bui.isWebapp = false;
    // 请求使用原生
    bui.config.ajax = {
        needNative: true
    }
    // 列表请求使用原生
    bui.config.list = {
        needNative: true
    }
    // 模块的import本地文件使用原生
    window.loader = bui.loader({
        needNative: true
    })
}
