### ISSUE TITLE
有关页面firstload正常，但是跳转load过来时诡异的问题。

### ISSUE THREAD

**Issue by matols** [imouou/BUI-Guide#148]
在当前页面的firstload时，一切数据加载、控件初始正常。

但是我从其他页面跳转的load过来时，init初始化也都执行了，额外进行数据请求也正常获取到了。但是，页面只渲染了部分，并且部分组件的初始化貌似没有执行，无法操作。单独的刷新一下当前页面又都一起正常了。（有关bui.load、单页路由、页面生命周期都已经反复排查了很多次，无解）

就是单纯的从其他页面跳转过来：
router.load({ url: "pages/main/main.html",param: { "tid":"600036"} });

还请帮忙分析解答。或者说有没有办法强制跳转过来的也是firstload？

**Comment by imouou** [comment]
如果你的首页默认是 `pages/main/main.html`  则 建议使用后退到main模块的处理, 可以具体查看 router.back 的参数说明, 但使用上一般 bui.back 执行.  如果非要跳转, 则使用 bui.load({ url:"main",param:{}})  跳转首页的方式. 再一个, 排查单页里面的选择器, $ 有没有替换成 router.$ 这个会影响重复跳转的页面上的DOM选择器. 文档的路由都有说明

**Comment by matols** [comment]
首先，非常感谢你的解答！

应用场景是：
1默认首页就是main，操作是在首页上点击跳转到其他列表页面，然后列表页面点击传参返回首页。
2根据你的解答，我调整了首页的router.$，看起来组件已经初始化了。

存在的问题：
首页有第三方的AntV F2的图表组件，还是存在异常。猜测是它的组件里的$选择器的冲突问题，不知该如何解决？

**Comment by imouou** [comment]
相同的页面正确使用路由的话, 一般不会有冲突问题的, 返回首页不是再执行一次跳转首页, 因为再次执行以后页面就会有相同的DOM,  图表的初始化一般有一个id, 那个id传 router.$("#id")[0]  这样去初始化应该也是可以的.

**Comment by matols** [comment]
第三方是那种声明式的方式：id就是
chart3 = new F2.Chart({
					id: 'mt3',
					pixelRatio: window.devicePixelRatio,
					height: 280,
					forceFit: true,
					padding: [40, 20, 20, 35] // 上右下左
				});

**Comment by imouou** [comment]
chart3 = new F2.Chart({
id: router.$('#mt3')[0],
pixelRatio: window.devicePixelRatio,
height: 280,
forceFit: true,
padding: [40, 20, 20, 35] // 上右下左
});
