### ISSUE TITLE
现在感觉非常后悔用 BUI 项目做到一半，官网随时打不开，一天挂5-6次，反正就是随缘

### ISSUE THREAD

**Issue by webasp** [imouou/BUI-Guide#149]

**Comment by webasp** [comment]
希望官方重视一下

**Comment by imouou** [comment]
官网一直很稳定, 域名没有备案只能使用国外空间, 目前的国外空间大部分地区都访问很快, 由于每个地区的线路是不一样的, 对外的线路也会不一样, 比如联通, 对外正常访问就很慢, 你可以试试把手机开启个热点, 如果是移动网络, 访问easybui.com 是很快的. 
当然在网络太慢的情况下, 你依然有其它方式本地查看.
第1. 官网下载的控件示例里面, 有每个控件的使用方法以及API查询, 如果官网打不开, 可以从https://github.com/imouou/BUI-Demo 这里clone下来;
第2. 你当前留言的便是官网的使用文档, 控件文档, 都可以 clone 下来. 

当然我们也在积极备案把网站迁移回国内, 可以多留意官网交流群的信息, 有问题也欢迎提出来, 熟悉以后你都不需要查阅文档.

**Comment by imouou** [comment]
也可以试试我们的备用站, www.buiapp.com 先测试看看稳定怎样.

**Comment by imouou** [comment]
部分地区如无法访问, 可以试试我们的备用站, http://buiapp.com
