### ISSUE TITLE
引入fixStatusBar.js后底部被main挤下去

### ISSUE THREAD

**Issue by weiwuying123** [imouou/BUI-Guide#15]
apicloud打包后引入fixStatusBar.js后 底部被main挤下去，这是怎么回事啊

**Comment by imouou** [comment]
这个只是针对iphone 及 iphonex 打包全屏做的处理, 你是安卓也会? 还是没有设置全屏?

**Comment by weiwuying123** [comment]
iPhone是这样的 全屏打开了 我看样式上像是main部分的高度把footer挤下去了

**Comment by weiwuying123** [comment]
我找到了解决办法 给footer加上.bui-fixed-bottom的类名就可以了，谢谢大神！
