### ISSUE TITLE
有关BUI打包后图片无法显示的问题

### ISSUE THREAD

**Issue by 04173176** [imouou/BUI-Guide#151]
将BUI用Hbuilder快速打包后，为什么在APP上无法显示图片呢？打包完之后文件也没有改变，图片的相对路径应该不会变的？我们在网页上都可以正常显示！！！很着急，或者可以怎么改？

**Comment by imouou** [comment]
所有文件路径的写法都应该用相对路径, 不能使用绝对路径, `images/xxx.jpg`  不能 `/images/xxx.jpg`
