### ISSUE TITLE
请教一个bui-navbar布局的问题

### ISSUE THREAD

**Issue by openpython** [imouou/BUI-Guide#153]
使用<ul id="nav" class="bui-nav">布局多个选项卡时滑动切换会把导航菜单调出了。页面的选项卡有30多个，无法所有滑动切换，请问如何设置出现左右箭头，方便浏览者点击滚动选项卡？
![1112020-03-04_003945](https://user-images.githubusercontent.com/1044542/75798117-13bd7780-5db1-11ea-9b78-73146c6e7760.jpg)

**Comment by imouou** [comment]
布局可以参考 http://www.easybui.com/demo/#pages/ui_controls/bui.tab_scroll  
移动端少有再使用箭头操作的方式, tab 可以是动态异步加载, 参考demo 的动态选项卡, 按需加载就行.

**Comment by openpython** [comment]
单独使用tab_scroll是正常的，加上菜单就不兼容了，下面是在演示案例上加入菜单代码，滑动tab会触发菜单弹出。`<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<title>BUI示例</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/buijs/lib/latest/bui.css">
		<script src="https://cdn.jsdelivr.net/npm/buijs/lib/zepto.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/buijs/lib/latest/bui.js"></script>
		<style></style>
	</head>
	<body>
	
	<div id="sidebarWrap" class="bui-sidebar-wrap">
	
	<div class="bui-sidebar swiperight">
		
		<ul class="bui-list">
            <li class="bui-btn bui-box">
                <div class="icon"><i class="icon-alert"></i></div>
                <div class="span1"><a href="/coins">菜单1</a></div>
                <i class="icon-listright"></i>
            </li>
            <li class="bui-btn bui-box">
                <div class="icon"><i class="icon-face warning"></i></div>
                <div class="span1"><a href="#">菜单2</a></div>
                <i class="icon-listright"></i>
            </li>
            <li class="bui-btn bui-box">
                <div class="icon"><i class="icon-chat success"></i></div>
                <div class="span1"><a href="#">菜单3</a></div>
                <i class="icon-listright"></i>
            </li>
            <li class="bui-btn bui-box">
                <div class="icon"><i class="icon-setting primary"></i></div>
                <div class="span1"><a href="#">菜单4</a></div>
                <i class="icon-listright"></i>
            </li>
            
            
        </ul>

	</div>

	
	
	<div class="bui-page">
    <header class="bui-bar">
        <div class="bui-bar-left">
            <a class="bui-btn" onclick="bui.back();"><i class="icon-back"></i></a>
        </div>
        <div class="bui-bar-main">
            滑动选项卡
        </div>
        <div class="bui-bar-right">
        </div>
    </header>
    <main>
        <div id="uiNavbar" class="bui-navbar">
            <ul id="nav" class="bui-nav"><li class="bui-btn">集团新闻</li><li class="bui-btn">图片新闻</li><li class="bui-btn">会议安排</li><li class="bui-btn">舆情监控</li><li class="bui-btn">版块动态</li><li class="bui-btn">其它版块</li><li class="bui-btn">版块动态A</li><li class="bui-btn">其它版块B</li></ul>
        </div>
        <div id="uiTabNavbar" class="bui-tab">
            <div class="bui-tab-main">
                <ul>
                    
                    <li><img src="images/placeholder-list.png" alt=""></li>
                    <li style="display: none;"><img src="images/placeholder-list.png" alt=""></li>
                    <li style="display: none;"><img src="images/placeholder-list.png" alt=""></li>
                    <li style="display: none;"><img src="images/placeholder-list.png" alt=""></li>
                    <li style="display: none;"><img src="images/placeholder-list.png" alt=""></li>
                    <li style="display: none;"><img src="images/placeholder-list.png" alt=""></li>
                </ul>
            </div>
        </div>
    </main>
</div>

</div>
<script>bui.ready(function(){

var uiSidebar = bui.sidebar({
        id: "#sidebarWrap", //菜单的ID(必须)
        width: 644,
        trigger: "#menu"
    });
    
    var uiTab = bui.tab({
            id:"#uiTabNavbar",
            menu:"#nav",
        });
    
     // 让顶部导航滚动到可视位置
     uiTab.on("to",function (index) {
            var left = $("#nav li")[index].offsetLeft;
            document.getElementById("uiNavbar").scrollLeft = left;
     })
})

</script>
</body>
</html>
`

**Comment by imouou** [comment]
两种做法:
1. `uiSIdebar.lock()` 调用这个方法可以阻止滑动触发菜单, 改用按钮控制菜单;
2. 阻止导航菜单的滑动事件冒泡.
```js
    router.$("#uiNavbar li").on("touchmove", function(e) {
        e.stopPropagation();
    })
```

**Comment by openpython** [comment]
OK，用第二个方法。
