### ISSUE TITLE
配置下拉刷新

### ISSUE THREAD

**Issue by racheljoin** [imouou/BUI-Guide#155]
根据1.5.x版本文档，配置reload属性不允许下拉刷新，但是并不生效。

**Comment by imouou** [comment]
{... refresh: false }

**Comment by racheljoin** [comment]
refresh，我写错了，就是按照文档写的option就是refresh:false，但是会报错，给refresh值为一个function的时候就不报错了，感觉文档好想有些问题，没有起效果

**Comment by imouou** [comment]
只有布尔值, 试试更新版本, 这个设置以后, 不能下拉刷新的

**Comment by racheljoin** [comment]
行，谢谢你，我再试试看
