### ISSUE TITLE
官网已经好几天打不开了，建议换个免费的服务器，应该也比现在这好些！这框架有人用也是见了鬼

### ISSUE THREAD

**Issue by webasp** [imouou/BUI-Guide#157]
官网已经好几天打不开了，建议换个免费的服务器，应该也比现在这好些！这框架有人用也是见了鬼

**Comment by imouou** [comment]
官网服务器一直很稳定, 不稳定的是地方网络对国外的限制, 有种技术叫翻墙, 跟你讲过很多备用地址可以打开, github也有相关文档, 下载下来便是, 别老说些有的没的, 能用就用, 不用就不用, 我们有挣你一毛钱吗?
