### ISSUE TITLE
焦点图如何动态加载

### ISSUE THREAD

**Issue by flytyger** [imouou/BUI-Guide#16]
我的代码如下：
pageview.fouceImg=function (){
    	bui.ajax({
    		url: "abc.json",
            data: {}
    	}).then(function(res){
    		var html1="";
    		var html2="";
    		$.each(res,function(index,el){
    			html1+='<li><img src="'+el.imagesURL+'" alt=""><div class="bui-slide-title">el.Title</div></li>';
    			html2+=' <li>'+index+'</li>';
    		})
    		
    		$("#fouceImg").html(html1);
    		$("#fouceImgNum").html(html2);
    	})
        
      };
![image](https://user-images.githubusercontent.com/4123735/45752521-51275700-bc48-11e8-9555-b3fbff95edc7.png)
虽然数据有了，但图片和文字显示的很小，不知道是怎么回事

**Comment by imouou** [comment]
图片没拉伸处理的, 这种一般用大图比较合适, 静态渲染会比较灵活, 按示例来就可以的

**Comment by flytyger** [comment]
我这是一个大图，如果用静态渲染没有问题，但转到动态加载就有问题

**Comment by imouou** [comment]
这个跟静态渲染或者动态渲染没有太大关系的, 主要是样式,处理好就可以了

**Comment by imouou** [comment]
> 我这是一个大图，如果用静态渲染没有问题，但转到动态加载就有问题

动态渲染就是在你请求渲染html 结构以后, 再初始化控件就可以了
