### ISSUE TITLE
一直以来，有关单页面路由跳转的问题

### ISSUE THREAD

**Issue by matols** [imouou/BUI-Guide#162]
楼主好！
使用BUI已经做了两个APP了，其他都很完美，尤其是丰富的实例。
但是，做的APP都有一个共通问题没解决，始终困扰这我，很难受！还请赐教！

文档上讲：从首页 main 跳转到登录页, 在登录的时候,就应该使用后退页面刷新或者局部刷新处理, 而不是使用 bui.load 继续跳转;

我实际的情况是，点击个人中心（发现没有登录）跳转到登录页（load方式），到了登录页，点击注册（load方式），注册成功。跳转到登录页（load），登录成功，跳转到首页（load）。

在这个跳转的过程中，时不时的会莫名的页面按钮点击没反应，要么就是事件冲突了，明明输入了值，却一直说是没有值，导致要么无法注册，要么无法登录。

虽然，我也理解你说的首页跳转登录，登录返回首页。但问题是，一方面浏览器没法测，另一方面，如果像这种多级跳转，没办法这样返回怎么弄？

还请赐教，我保证你的文档我已经反反复复的琢磨了，但还是有困惑，求赐教！！！

**Comment by imouou** [comment]
前面其实也很多人在问这个问题, 但估计文档还有些没有太过留意, 单页里面, `$` 选择器 跟 `router.$` 的区别是什么?  $ 是从文档html开始查找元素, router.$ 是从单页的唯一id开始查找, 只有这样才能把单页里面的dom进行区分. 如果有替换过这个, 应该页面重复加载是不会导致不触发的. 

再谈另外一个问题, 就是登录以后, 页面已经加载, 继续跳转, 页面继续加载, 所以控制不好路由, 就会导致页面重复的内容太多, 我们推荐的是加载过的页面采用后退处理, 粗暴一点就是后退直接调用 bui.refresh 这个 1.6可以这样用. 

比方, 你点击个人中心, 没登录, 跳转登录, 发现没有注册, 再点击注册, 那注册完以后, 根据页面已经加载的原则, 那不是应该采用后退的方式回到登录页吗? 点击登录,再后退回到首页, 这样整个路由是完整的. 

关于登录, github 里面有个 bui-login 的库, 写了几种常用的登录的处理方案, 可以自行查看代码.

**Comment by matols** [comment]
router.$的问题，已经特别留意处理了，可有时候还是会有点问题。尤其是三个以上的链路，没法简单返回那种。
当时确实是想过使用 bui.refresh简单粗暴处理，可是会导致刷新死循环（1.5）。

**Comment by imouou** [comment]
你可以新建个简单的工程, 看看能否重现你说的问题, 目前看正常有替换 router.$ 的话, 事件绑定,选择器都是正确的处理.   后退 bui.refresh 1.5的不能直接这样用, 会造成重复绑定等问题
