### ISSUE TITLE
有内置主题,支持黑暗模式么

### ISSUE THREAD

**Issue by yezi34880** [imouou/BUI-Guide#169]

**Comment by imouou** [comment]
下一个版本可能会新增深色皮肤.

**Comment by yezi34880** [comment]
下一版什么时候发呢

**Comment by imouou** [comment]
预计月底有一版

**Comment by yezi34880** [comment]
了解了,看了你们的框架感觉还不错,比framework7要轻,比weui/mui一众要全,似乎也更适合国人写法,感觉挺好的,但目前现在做WebApp为了上IOS必须要有黑暗模式,稍后出来再看吧

**Comment by imouou** [comment]
这个暗黑模式确定不是指原生层面的? 样式都是可调的, 根据需要调整也不会影响的.
