### ISSUE TITLE
进入页面时bui.list发送了5次请求数据

### ISSUE THREAD

**Issue by 18068280110** [imouou/BUI-Guide#17]
首次进去列表页面时，不知道为什么了连续发送了5次请求
var uiList = bui.list({
		id: "#scrolPlanList",
		// 测试的接口及传参
		url: serverUrl + "/main/test",
		data: {
			"id":1
		},
		pageSize:10,
		height:0,
		template: templateList,
		method:"POST",
		//如果分页的字段名不一样,通过field重新定义
		field: {
			page: "pageNum",
			size: "pageSize",
			data: "datas"
		},
		onRefresh: function (scroll) {
			//刷新的时候执行
		},
		onLoad: function (scroll) {
			// console.log( this.option("page") );
		}
	});

**Comment by imouou** [comment]
根据你的高度会继续请求下一页数据, 如果你的10条数据还不足以撑满页面,则会继续请求, 直到没有数据
