### ISSUE TITLE
如何判断滚动条位置 ，直接原生 无法判断到

### ISSUE THREAD

**Issue by ThedoRap** [imouou/BUI-Guide#170]

**Comment by ThedoRap** [comment]
还有滚轮触发  使用原生代码无法调用

**Comment by ThedoRap** [comment]
$('#scrollList').on('scroll',function(){
        console.log( $('#scrollList').scrollTop())
    })

**Comment by imouou** [comment]
先找到你滚动条的位置的dom, 这样不贴代码别人不知道你里面有多少个滚动元素. 另外移动端没有滚轮的
