### ISSUE TITLE
动态表单取值问题

### ISSUE THREAD

**Issue by xuxuncheng** [imouou/BUI-Guide#171]
请问动态表单中如何获取表单中的值？
官网例子并不能获取到值
![QQ截图20200718174327](https://user-images.githubusercontent.com/44454356/87849836-56c25680-c91e-11ea-95d9-3a43f83876a2.png)

**Comment by imouou** [comment]
以demo为主，源码里查看的示例不一定能正常初始化 http://www.easybui.com/demo/#pages/store/form_dynamic



来自 魅蓝 Note6



-------- 原始邮件 --------
发件人：xxc <notifications@github.com>
时间：2020年7月18日 17:46
收件人：imouou/BUI-Guide <BUI-Guide@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[imouou/BUI-Guide] 动态表单 (#171)


请问动态表单中如何获取表单中的值？
官网例子并不能获取到值
[QQ截图20200718174327]<https://user-images.githubusercontent.com/44454356/87849836-56c25680-c91e-11ea-95d9-3a43f83876a2.png>
