### ISSUE TITLE
dist  打包（npm build）

### ISSUE THREAD

**Issue by 17754920131** [imouou/BUI-Guide#173]
我想知道的事，我的api在服务器上面并且用app.json做了代理，pc版上面运行没问题，但是通过Hbuderx打包成apk格式的时候手机上运行就连接不到api了，我能保证我手机上是和服务器在同一个局域网里面的就是取不到数据，而且我仔细看了打包的dist文件里面也没有保护app.json，所以我就想知道才能让手机上面的apk，获取的服务器上的数据

**Comment by imouou** [comment]
公众号 bui神速 有关于打包的教学，dcloud打包的安卓版本没有跨域问题，所以不会有app.json这些配置，这个仅供调试，你可以试试把接口部署在外网试试。



来自 魅蓝 Note6



-------- 原始邮件 --------
发件人：17754920131 <notifications@github.com>
时间：2020年7月31日 09:45
收件人：imouou/BUI-Guide <BUI-Guide@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[imouou/BUI-Guide] dist 打包（npm build） (#173)


我想知道的事，我的api在服务器上面并且用app.json做了代理，pc版上面运行没问题，但是通过Hbuderx打包成apk格式的时候手机上运行就连接不到api了，我能保证我手机上是和服务器在同一个局域网里面的就是取不到数据，而且我仔细看了打包的dist文件里面也没有保护app.json，所以我就想知道才能让手机上面的apk，获取的服务器上的数据
