### ISSUE TITLE
想请问一下bui框架对其他js框架，有哪些依赖？

### ISSUE THREAD

**Issue by CasualMing** [imouou/BUI-Guide#175]
因为我看了一下bui官网的文档，许多示例都是用了jQuery或者zepto，就是想请问一下bui框架是依赖了哪些第三方插件？如果有时间能否加在文档上，这样可以让开发者更直观的了解到项目中用到的技术及文件。这样在不适用的情况下，可以有更大的自主选择权？

**Comment by imouou** [comment]
jquery或者zepto ，没别的了



-------- 原始邮件 --------
发件人：xiaoMingTongXue <notifications@github.com>
时间：2020年8月29日 23:41
收件人：imouou/BUI-Guide <BUI-Guide@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[imouou/BUI-Guide] 想请问一下bui框架对其他js框架，有哪些依赖？ (#175)


因为我看了一下bui官网的文档，许多示例都是用了jQuery或者zepto，就是想请问一下bui框架是依赖了哪些第三方插件？如果有时间能否加在文档上，这样可以让开发者更直观的了解到项目中用到的技术及文件。这样在不适用的情况下，可以有更大的自主选择权？
