### ISSUE TITLE
bui.array.remove方法无法删除问题

### ISSUE THREAD

**Issue by Alivan-P** [imouou/BUI-Guide#176]
var arr = [{ "id":0,value:"hello"},{ "id":1,value:"bui"}];
 var newArr = bui.array.remove( arr, 0, "id" );
console.log(newArr);
当id从0开始时，无法删除id为0的元素。

**Comment by imouou** [comment]
收到, 会在下一个版本修正

**Comment by imouou** [comment]
可以先用CDN的版本下来使用 https://cdn.jsdelivr.net/npm/buijs@1.6.31/lib/latest/bui.js
