### ISSUE TITLE
关于无法在bui.ready中使用全局loader.global的问题

### ISSUE THREAD

**Issue by Alivan-P** [imouou/BUI-Guide#177]
您好，我结合官方文档“**组件全局方法**”一节，使用`loader.global()` 来定义了全局方法，
全局方法定义如下，与官方文档完全一致，代码位于`js/global.js`文件中:
```javascript
loader.global(function(global){
    return {
      config: {},
      getDate: function(){
        console.log("获取日期")
      }
    }
})
```
但是在使用中发现无法全局调用，即以下代码不能正常工作：

```javascript
bui.ready(function(){
	// 全局调用
	// Error：无法获取到loader.globals，此时loader.globals===undefined
	loader.globals.getDate();
});
```
**PS**:
- 以上代码位于程序入口文件`index.js`中
- `index.html`中已引入`global.js`文件。
- 引用顺序如下：
```javascript
<script src="js/zepto.js"></script>
<script src="js/bui.js"></script>
<!--全局配置-->
<script src="js/global.js"></script>
<!-- 初始化单页 -->
<script src="index.js"></script>
```
- 在模块中可以正常调用：
```javascript
loader.define(function(require,exports,module,global){
  	// 模块调用
  	// Right：getDate方法正常工作，输出："获取日期"
  	global.getDate();
});
```
- bui.js版本1.6.2支持原生版。 

所以想请问一下到底是哪里出了问题？

**Comment by imouou** [comment]
这个问题在新版修复还没发布, 可以先从cdn上获取 https://cdn.jsdelivr.net/npm/buijs@latest/lib/latest/bui.js

全局调用使用  loader.global().getDate();

**Comment by Alivan-P** [comment]
更新版本后`loader.global().getDate()`工作正常。
感谢回复。
另外：
1.有渠道可以获取你们cdn上的更新日志吗，或许可以根据更新日志帮助我们快速解决一部分问题。
2.当前cdn发布的最新版是否是支持原生版，如果不是，替换之后对dCloud打包会产生什么影响？

**Comment by imouou** [comment]
更新日志只有发布的时候才会在官方文档提供, CDN的发布更多的是测试版, 不能用于生产环境, 一些紧急的修复会通过cdn解决.
目前cdn版本只有 webapp版本, 对dcloud的开发没有影响, 后面打包的时候更新发布的原生版就行.

**Comment by Alivan-P** [comment]
新版本的原生版预计什么时候发布呢，有排上日程吗？：）

**Comment by imouou** [comment]
可能在月底,你也可以关注 bui-template 这个库, 有时候更新不一定会发版本
