### ISSUE TITLE
BUI 1.6.2的zepto.js不支持$(...).nextAll，导致BUI 1.5.1的项目运行不正常

### ISSUE THREAD

**Issue by wanshijiain** [imouou/BUI-Guide#178]
项目原来使用BUI 1.5.1及相应的zepto.js，
最近升级到BUI 1.6.2及相应的zepto.js，发现功能不正常，检查到$(...).nextAll()不支持，而旧版本是支持的。

**Comment by imouou** [comment]
bui 自1.4以来都是使用同一个版本的 zepto.js , 这个版本是简化版的 jquery 是没有 nextall 等api 的, 你可以独立引入 jquery 或者找到 zepto.js 的插件会有这方面的api , 可以替换成你需要的版本.
