### ISSUE TITLE
1.6.2版本 BUI.searchbar输入多个字符时请求发送太频繁，1.5.1版本没有此问题

### ISSUE THREAD

**Issue by wanshijiain** [imouou/BUI-Guide#179]
项目原本使用BUI 1.5.1，在BUI.searchbar中搜索5555，只发送了一次搜索请求。
更新到BUI 1.6.2，在BUI.searchbar中搜索5555，发送了四次搜索请求，每输入一次请求一次。太频繁了担心影响性能。
两次输入速度是差不多的，不是速度的问题。

![BUI1 5 1只发送一次请求](https://user-images.githubusercontent.com/24598742/92928566-da597900-f471-11ea-98d0-2e200adf0bd7.png)
![BUI1 6 2发送多次请求](https://user-images.githubusercontent.com/24598742/92928595-e5aca480-f471-11ea-9fbe-55c470f63d7d.png)

**Comment by imouou** [comment]
这个是有这个问题, 1.5的版本是针对字符串做了处理, 1.6版本是对中文字符做了处理, 尽量模拟真实的需求, 后续新版会尝试兼容两种输入优化的.
