### ISSUE TITLE
levelselect 增加ID 属性

### ISSUE THREAD

**Issue by diysoho** [imouou/BUI-Guide#18]
levelselect 目前是文本，可否优化为 ID+ 文本，这样插入数据库可以插入对应的id。

<div id="v1" class="selected-val" rel=‘ID’>文本内容</div>

**Comment by diysoho** [comment]
` <div id="v1" class="selected-val" rel=“ID”>文本内容</div>`

**Comment by imouou** [comment]
levelselect 会把你的数据的所有非对象字段, 遍历在每行的 input 上, 你可以监听每次改变的时候, 通过 e.target.id 把数据缓存下来, 这样你插入数据库则可以有对应的ID
