### ISSUE TITLE
使用cordova 为啥打包到 ios 找不到页面，android 平台可以

### ISSUE THREAD

**Issue by cloudcitys** [imouou/BUI-Guide#180]
使用 cordova 编译 bui 项目，安卓端可以运行，打包 ios后报错，找不到页面

[Error] Cross origin requests are only supported for HTTP.
	
[Error] XMLHttpRequest cannot load 
file:///Users/yuncheng/Library/Developer/CoreSimulator/Devices/DE2743D0-FC54-4CD8-B28E-2C98A5C7DDC3/data/Containers/Bundle/Application/891ACB81-63F4-4CBC-9901-9DFEE068DE72/mytest.app/www/pages/main/main.html due to access control checks.
	
[Error] bui.router.load 找不到页面 pages/main/main.html

这个是ios 模拟器控制台的消息
<img width="1327" alt="截屏2020-09-17 下午9 49 42" src="https://user-images.githubusercontent.com/42485290/93480173-bc878a80-f92f-11ea-81e1-c79c39155842.png">

**Comment by imouou** [comment]
苹果IOS默认使用的是 WKWebview, 已经不允许跨域了, 只能通过转换原生请求的方式, 你试试给cordova 加上 HttpRequest 插件, 然后在首页修改 index.js 第一行加上 window.loader = bui.loader({ needNative: true});   可以的话, 还需要修改所有请求走原生. 
bui.config.ajax = { needNative: true};
bui.config.list = { needNative:true };

或者使用cordova 打包的webview选择 UIWebview  就没有这种问题. Dcloud平台其它平台都是类似的方案.
