### ISSUE TITLE
1.5.1升级到1.6.2后，BUI.List不能自动计算适配高度且页面无法滚动

### ISSUE THREAD

**Issue by wanshijiain** [imouou/BUI-Guide#181]
1.5.1升级到1.6.2后，BUI.List不能自动计算适配高度（.bui-scroll的div元素style缺少height）且页面无法滚动。将bui.js单个文件还原到旧版本功能正常。
两个版本的页面效果如下图（列举两个功能）
功能一：
![BUI1 5 1中bui list对象自动计算高度页面可滚动](https://user-images.githubusercontent.com/24598742/94549742-40713900-0285-11eb-8950-d8b50ff1b5a3.png)
![BUI1 6 2中bui list对象没有自动计算高度页面不可滚动](https://user-images.githubusercontent.com/24598742/94549821-5aab1700-0285-11eb-8fce-443ce80223f7.png)

功能二：
（bui.list 的父div style height有值，但值不对，导致滚动区间很小）
![功能二1 5 1版本功能正常](https://user-images.githubusercontent.com/24598742/94552070-e8d4cc80-0288-11eb-8a09-bc1f4e90284c.png)
![功能二1 6 2版本功能不正常](https://user-images.githubusercontent.com/24598742/94552099-f12d0780-0288-11eb-806b-68b5b4668bf4.png)

是否有接到反馈此类问题？

**Comment by wanshijiain** [comment]
由于看不到上传图片，文字说明下。
功能一页面
1.5.1版本 .bui-scroll div的正确高度为height: 704px;
1.6.2版本 .bui-scroll div的height未给定值，页面无法滚动。
功能二页面
1.5.1版本 .bui-scroll div的正确高度为height: 754px;
1.6.2版本 .bui-scroll div的高度为height: 50px;，导致滚动区间很小。

**Comment by imouou** [comment]
第1个问题, 没有使用bui标准页面结构, 升级我们无法保证你的结构是能正常的, 但是我们的肯定可以, 按标准开发, 官方示例都是正常的情况下, 查看源代码有什么不同就能找到答案.  
http://www.easybui.com/demo/source.html?url=pages/ui_controls/bui.searchbar&code=html,js,result
按bui的新标准页面结构,可以把搜索栏放到头部. 
第2个问题, tab跟list的使用, 新版现在更加简单 http://www.easybui.com/demo/#pages/ui_controls/bui.tab_component 
bui-scroll 如果是占满父级全屏,可以加上 fullheight 样式
