### ISSUE TITLE
bui 分页加载问题

### ISSUE THREAD

**Issue by chenguijie** [imouou/BUI-Guide#182]
bui的分页加载会出现一次性全部请求多个分页的数据,这个bug是什么原因导致的

**Comment by imouou** [comment]
一次性全部请求多个分页?  
1. 一次性把所有分页数据全部请求?  
2. 还是一次会有请求多个分页的情况?

如果是第1种情况, 检查接口, 官方的测试接口是静态数据, 当然是一次性全部请求, 但你可以看到network里面的分页及传参都是不一样的, 关注这个就行. 
如果是第2种情况, 这是控件的设计本来如此, 如果pageSize为5条, 第一次请求5条数据以后, 还不足以撑起滚动条, 就会继续请求下一页数据, 直到有滚动条为止. 所以如果想一次请求一页, 改大一下每次请求分页的大小就行.

**Comment by chenguijie** [comment]
您好,不知道该怎么说,就是请求完一个分页的数据后,没有滚动就自动开始请求第二个分页的数据(滚动条都已经撑开了0v0,并不是滚动条没撑开)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imouou/BUI-Guide"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 上午10:38
收件人:&nbsp;"imouou/BUI-Guide"<BUI-Guide@noreply.github.com&gt;;
抄送:&nbsp;"停下就很难起来了"<1814219942@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [imouou/BUI-Guide] bui 分页加载问题 (#182)





 
一次性全部请求多个分页?
  
一次性把所有分页数据全部请求?
 
还是一次会有请求多个分页的情况?
  
如果是第1种情况, 检查接口, 官方的测试接口是静态数据, 当然是一次性全部请求, 但你可以看到network里面的分页及传参都是不一样的, 关注这个就行.
 如果是第2种情况, 这是控件的设计本来如此, 如果pageSize为5条, 第一次请求5条数据以后, 还不足以撑起滚动条, 就会继续请求下一页数据, 直到有滚动条为止. 所以如果想一次请求一页, 改大一下每次请求分页的大小就行.

**Comment by imouou** [comment]
1. 看看有没有初始化多次的情况了;
2. 看看field 参数配置是否正确;
3. 尝试改大pageSize参数, 一次返回更多数据;
 目前控件在N多个项目使用正常, 可以新建个简单例子去排查,  如果请求的分页及传参正确, 大可不必纠结第一次请求多少了多少页.
