### ISSUE TITLE
bui.upload无法拉起安卓相机

### ISSUE THREAD

**Issue by HiWangYing** [imouou/BUI-Guide#183]
**问题：点击后会弹出选择图片的页面**
![Uploading image.png…]()

版本：1.5.1
手机型号：红米7
系统版本：android9
代码片段：
`
var uiUpload = bui.upload({
  showProgress: true,
  // needNative: false
 });

uiUpload.add({
    "from": "camera",
    "mediaType": "camera",
    "onSuccess": function(val, data) {
        this.toBase64({
            onSuccess: function(url) {
            	console.info(url)
                $uploadBtn.before(templatePhoto(url, val[0].name))
            },
            onFail: function(url) {
                bui.alert(url)
            }
        });
    }
})
`

**Comment by imouou** [comment]
以官方例子为准, http://www.easybui.com/demo/#pages/ui_controls/bui.upload  
点击源码可以看到不同的方式用的不同的方法.

**Comment by HiWangYing** [comment]
官方的这个页面(html,js)我原样复制到手机上了，但点击拍照上传，仍然是跳转到相册的页面。（分别在三个手机上测试了，红米7,华为nova5 pro,nova5 i 均跳转到了相册）
无法直接拉起相机。
是我哪个全局设置漏掉了么，希望可以指点一下。谢谢

**Comment by imouou** [comment]
你再试试在微信里面测试, 基本都是可以的, 之所以浏览器不可以是因为浏览器的版本较低, 不支持没有唤起相机的权限, 需要先通过文件,再选择相机... 如果是打包, 可以使用原生拍照的api.. 浏览器的api取决于浏览器的内核.

**Comment by HiWangYing** [comment]
已解决，解决思路（声明：本人为后端开发，所展示的解决方案可能有冗余代码，仅供参考，欢迎交流指正）
1.在AndroidManifest.xml添加<uses-permission android:name="android.permission.CAMERA" />声明要使用到相机权限
2.页面代码，在官方给出的拍照上传点击事件改成调用getImage()方法，代码如下
`function uploadPics(url) {
	        var img = new Image();
	        img.src = url;
	        img.onload = function() {
	            var that = img;
	            var w = that.width,
	                h = that.height,
	                scale = w / h;
	            w = 320 || w;
	            h = w / scale;
	            var canvas = document.createElement('canvas');
	            // var base64 = canvas.toDataURL('image/png', 'image/jpeg', 'image/jpg', 1 || 0.8);
	            var ctx = canvas.getContext('2d');
	            $(canvas).attr({
	                width: w,
	                height: h
	            });
	            ctx.drawImage(that, 0, 0, w, h);
	            var base64 = canvas.toDataURL('image/png', 'image/jpeg', 'image/jpg', 1 || 0.8);
	            // bui.alert(base64)
	            // bui.alert(templatePhoto(base64, "123"));
	            $uploadBtn.before(templatePhoto(base64, "123"));
	        }
	    }

	    function getImage() {
	        var cmr = plus.camera.getCamera();
	        cmr.captureImage(function (p) {
	            bui.alert('成功：' + p);
	            plus.io.resolveLocalFileSystemURL(p, function(entry) {    
	                bui.alert("真实路径："+entry.fullPath);
	                var localurl = entry.toLocalURL();
	                uploadPics(localurl)
	            }, function(e) {    
	                bui.alert(e.message);    
	            }); 
	        }, function (e) {
	            bui.alert('失败：' + e.message);
	        }, {
	            filename: '_doc/camera/',
	            index: 1
	        });
	    }`
