### ISSUE TITLE
能否出视频教程

### ISSUE THREAD

**Issue by dssxyz** [imouou/BUI-Guide#188]
我感觉bui很好用，但是我是刚毕业的，看文档学起来不如看视频学的快速。

**Comment by imouou** [comment]
谢谢, 早期bui官方有录制过视频, 但视频跟不上更新的速度, 后面就没有继续了, 有热心网友TigerChain 自己录制了一些视频, 虽然不一定全对, 但对于入门的理解是有帮助的. 最好的bui的学习办法是根据官方的demo操作,查看源码, 有几百个示例, 学会一个以后, 熟悉一遍即可基本掌握BUI. 
https://www.bilibili.com/video/BV1Ft411A7Wj?from=search&seid=7468349368725691739 
https://www.bilibili.com/video/BV1u4411r7FG?from=search&seid=7468349368725691739
