### ISSUE TITLE
bui.actionsheet 点击后一直alert 0

### ISSUE THREAD

**Issue by qq312785889** [imouou/BUI-Guide#189]
这里获取的value值一直是0，请问怎么解决

**Comment by qq312785889** [comment]
![image](https://user-images.githubusercontent.com/39783725/111095541-9b1ef880-8578-11eb-9a73-d43b3029b7f1.png)

**Comment by imouou** [comment]
看你截图的代码, 这个应该是用在后台源码上, 导致了 $ 跟 后端的保留字符冲突了... 可以试试 `var val = e.target.getAttribute("value")`
