### ISSUE TITLE
因项目需要，如何使用深层目录方式

### ISSUE THREAD

**Issue by runtuer** [imouou/BUI-Guide#193]
原本pages是放根目录下的，域名直接指向到该目录即可正常访问，但因项目需要，必须采用深层目录，也就是说，pages目录放的很深，想请教一下，如何对所有页面都使用深层目录方式，比如：http://www.xxx.com/aa/bb/cc/index.html#pages/register

**Comment by imouou** [comment]
把原本dist的整个目录下剪切到 `aa/bb/cc/` 目录里面，无需修改页面跳转路径。如果你原本的路径写法是 `/pages/resister` 则会从根目录开始查找,这种是不被建议的.
