### ISSUE TITLE
echarts现在用不了

### ISSUE THREAD

**Issue by duyishuaixue** [imouou/BUI-Guide#195]
现在echarts用不了了，怎么都报错，说require问题，怎么破呀？

**Comment by imouou** [comment]
官网例子已经更新，原本的echart依赖地址更新了，http://easybui.com/demo/#pages/thirdpart/chart/echart

**Comment by duyishuaixue** [comment]
> 官网例子已经更新，原本的echart依赖地址更新了，http://easybui.com/demo/#pages/thirdpart/chart/echart

好的呀，可以了，谢谢一直更新回复。感谢感谢
