### ISSUE TITLE
单页面路由使用echarts为什么报这个错呀？一直解决不了，麻烦看看谢谢了

### ISSUE THREAD

**Issue by duyishuaixue** [imouou/BUI-Guide#196]
<img width="1080" alt="错误日志" src="https://user-images.githubusercontent.com/10572865/123031786-74921880-d417-11eb-8afe-fc2e5f59a528.png">

**Comment by duyishuaixue** [comment]
已解决，每次修改了文件需要重新打包才生效，实时预览总是报上门的错

**Comment by imouou** [comment]
BUI的模块本身采用动态加载的方式，而ES6使用静态编译的方式，如果页面使用 import,export 之类的参数就会导致实时预览报错，这种静态编译需要最终打包成一个文件才能找到对应依赖，这种方式如果模块依赖越来越多，打包就会越来越慢，所以bui并不推荐这种方式引入模块，其它es6都能正确编译。
