### ISSUE TITLE
打扰了

### ISSUE THREAD

**Issue by baobaomax** [imouou/BUI-Guide#2]
你好，感谢你提供的这个框架，我觉得很好用。但皮肤不是很好看，我在一个项目里，把bui.js 和 mdui.js 合用了，用了mdui的控件，用了bui的单页router框架，，，但两者好像配合的不是很好，有一个这样的问题：我用mdui做了复选框，但只有双击才会有效果，单击无效，然后我单独试了一个html文件，只有mdui.js，复选框单击有效，请问你有什么办法帮我解决吗，谢谢了！！！

**Comment by imouou** [comment]
bui.js 是一个手机端的webapp 框架哦, 不是bui pc 版, 你这里的mdui 也是pc 版的, 先确定你是否找错框架了?

**Comment by baobaomax** [comment]
哦，，，谢谢！因为material desing的手机ui不多，所以只能这样用了，之后我好像是找到了原因，就是mdui在label 里套了div，好像就会那样，我把div去了，好像就可以用了。。。。现在有另一个问题，关于模块的作用域，如果两个不同模块的html文件里有同样的id名，在模块对应js文件中调用这个id的时候可能会出错，模块里的id是全局的吗？还是说，每个模块的id都要用router.currentPage()来加以区分，但这样就显得很繁杂，如果一个模块里有多个控件，那可能就对应了好多个id，每个都调用currentPage的话，代码量就很大。请问你能不能让默认id就是本模块的，然后全局的就再给一个api，毕竟在自身模块里用id时，大多指的是本模块，而不是全局模块。。。不知我的表述是否清楚，真心希望你的这个框架能越来越好，谢谢！

**Comment by baobaomax** [comment]
对了，你能不能再美化一下bui的UI啊，mdui的按钮点一下就会有波纹出来，对于用户体验来说更具确定性，可以借鉴一下google的Materia Design或mdui，前端的用户体验对产品来说还是很重要的一个环节。我是一个高校的老师，我想借用你的框架做一个学生课堂app，现在主要处于前端界面、交互、逻辑阶段，可能以后还会碰到很多问题，到时还要来请教你哦，谢谢了！！！

**Comment by imouou** [comment]
嗯, 表达得很清楚, 那个currentPage 就是用来处理这个ID冲突的, 但确实是会比较繁琐, 这个新版有修复的, 可以不用过多关注ID重复的问题, 当然最好是避免这种重复加载的页面, webapp主要还是以轻为主,路由的切换不要让用户迷失. 至于您对UI的建议, 我们理解这种体验交互的重要性, 但我们也要在性能上做个取舍, 手机不比PC, 过多的动画消耗的性能如果反而导致应用的操作卡顿体验下降, 这个影响是不必要的, 我们目前采用的是按下去的时候有个轻微的高亮, 这些UI都可以根据自己的需求更改的. 再次谢谢你的建议及祝愿. 我们也希望在这个道路上有自己的方向.

**Comment by baobaomax** [comment]
哦，好的，，，期待新版出来，，谢谢！

**Comment by imouou** [comment]
已经更新了, 欢迎使用, 现在的控件初始化不需要过多关注这个唯一值了, 但是dom的事件绑定,及第三方的初始化, 可以查看 router.$() 选择器,返回的就是当前页的元素
