### ISSUE TITLE
bui.slide多次创建会导致scrollNum反复+1

### ISSUE THREAD

**Issue by kaiki** [imouou/BUI-Guide#203]
场景是需要创建多个相册，所以在每次创建的时候重新生成bui.slide，即使重复设置xxx.option({'scrollNum':1})也无效。
第一次创建，每次滑动的确是一个，但是第二次创建，每次滑动会变成两个，第三次则变成三个，类推。
暂无解决办法。

**Comment by kaiki** [comment]
完整代码
`     pageview.imgbox = function(){

        $("#bui-router").on("click", ".picture", function() {

            var index = xxx;

            var data = xxx;

            var uiImgboxDialog = bui.dialog({

                id: "#uiImgbox",

                fullscreen: true,

            })

            var uiImgbox = bui.slide({

                id: "#imgbox",

                fullscreen: true,

                autopage: true,

                bufferEffect: false,

                scrollNum:1,

                data: data

            });

            uiImgboxDialog.open();

            uiImgbox.to(index);

        });

    }`
html

<div id="uiImgbox" class="bui-dialog">
	<div class="bui-dialog-main">
		<div id="imgbox" class="bui-slide"></div>
	</div>
	<div class="bui-dialog-close"><i class="icon-close"></i></div>
</div>

**Comment by kaiki** [comment]
刚刚没转义
&lt;div id=&quot;uiImgbox&quot; class=&quot;bui-dialog&quot;&gt;
	&lt;div class=&quot;bui-dialog-main&quot;&gt;
		&lt;div id=&quot;imgbox&quot; class=&quot;bui-slide&quot;&gt;&lt;/div&gt;
	&lt;/div&gt;
	&lt;div class=&quot;bui-dialog-close&quot;&gt;&lt;i class=&quot;icon-close&quot;&gt;&lt;/i&gt;&lt;/div&gt;
&lt;/div&gt;

**Comment by imouou** [comment]
BUI的控件都不允许重复创建，可以在创建以后调用方法去修改对应的数据，可以尝试看看。

` pageview.imgbox = function(){

        var uiImgboxDialog = bui.dialog({

            id: "#uiImgbox",

            fullscreen: true,

        })

        var uiImgbox = bui.slide({

            id: "#imgbox",

            fullscreen: true,

            autopage: true,

            bufferEffect: false,

            scrollNum:1,

            data:[]

        });

    $("#bui-router").on("click", ".picture", function() {

        var index = xxx;

        var data = xxx;
// 通过实例修改渲染的数据的方式
        uiImgbox.option("data",data)

        uiImgboxDialog.open();

        uiImgbox.to(index);

    });

}`

**Comment by kaiki** [comment]
非常感谢，现在正常了
