### ISSUE TITLE
bui.pullrefresh在下拉后回拉，下拉高度会被取绝对值，而继续产生下拉效果

### ISSUE THREAD

**Issue by kaiki** [imouou/BUI-Guide#204]
gif图
[Imgur](https://imgur.com/K8rkBZ7)
一般来说在下拉后回拉，高度小于产生刷新的高度，应该视为放弃刷新了，bui无法放弃刷新，而且高度<0时会出现这种BUG。

**Comment by kaiki** [comment]
关于放弃刷新的描述可能有点不正确，更正一下：
放弃刷新的时候，refreshTips没有变更为end，还是release，但是放开时并没有执行刷新

**Comment by imouou** [comment]
是的，只是状态没有及时修改，不会触发执行刷新，下个版本会修正这个状态提醒
