### ISSUE TITLE
几个问题，关于page的侧滑关闭、物理返回键，以及图片的放大、下载等

### ISSUE THREAD

**Issue by kaiki** [imouou/BUI-Guide#206]
比如我现在开发的是一个微博程序，点击列表中的项目即可查看原文，如果用多页路由开发或将原文用load打开，那么就能侧滑关闭以及物理返回键返回，但是存在一些问题，iOS下会因为关闭时执行一次关闭动画，并回到上一个页面时再次执行一次关闭动画；如果使用前进或前进手势，那么又会重新打开刚刚已经关闭的页面，这不合理。
而我现在改用page开做原文的页面，这样就无法使用侧滑关闭和物理返回了，尝试写了一个侧滑关闭，但是手势会和page里面的list同时执行，就会出现横向和纵向同时滚动的情况。
既然是文章，那自然得有图片查看器，比如微博或者微信这种， 图片都可以放大、下载，目前用的相册写法，无法放大，长条的内容没办法正常查看，以及bui有下载保存图片的功能吗？

**Comment by imouou** [comment]
我大概理解你的意思，这里要分清楚是单页开发，还是多页开发。
多页开发，每个html独立加载各种依赖，每个js有一个 bui.ready 负责执行，这个跳转没有动画，传统的开发方式，这个应该没有你说的手势返回问题，但这种体验不太好，我们默认都是单页开发，跳转有动画，所以我猜测你说的是单页开发。

单页开发，一个html，一个js，html只有结构和样式，没有引入资源，js负责模块的内容与执行，这种跳转是有动画的，媲美app。

回到你说的问题，侧滑关闭跟物理回退，单页都是支持的，问题在你说的IOS手势返回，这个会有2个动画，一个是IOS系统层的动画，一个是页面的动画，手势拖拽第一层就是IOS动画，这个动画实际还没有真正的后退，所以会看到跳转2次才回到上一页，这个安卓是正常的。所以解决方案是，在src/index.js 判断是IOS，把路由初始化的动画，改成showIn, 或者fadeIn, 这样跳转跟后退都不会有动画，就没有手势后退这个问题。

bui.page 是用来局部加载的，像你说的跳转详情，一般是不建议使用这个，但比如评论，打开图片预览，这些是属于局部加载的，可以使用，目前的相册写法是不支持缩放的，因为这个在移动端体验不好，正常应该是使用原生的打开图片的能力。bui没有下载保存图片功能，这种应该使用原生平台去实现。

再说一个，侧滑跟系统自带的手势是冲突的，只能二选一，用了侧滑里面阻止了事件传播，所以不能使用系统手势，这种侧滑一般在首页，没有历史记录功能，所以不会跟手势冲突。一种是使用按钮打开侧滑，关闭掉控件的手势操作。

**Comment by kaiki** [comment]
我的确是单页开发的，使用page的原因是它不会导致左滑手势/前进按钮而重新打开被关闭的页面，比较无奈。
我不希望被关闭的页面因为使用前进而重新打开，有没有什么办法呢？

**Comment by imouou** [comment]
路由初始化有个同步历史记录的开关，具体查看API文档，关闭掉就不受前进后退的操控了
