### ISSUE TITLE
BUI 有PC的组件库吗

### ISSUE THREAD

**Issue by aoxiangsky** [imouou/BUI-Guide#208]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by imouou** [comment]
现在虽然专于移动端，但是大部分组件可以在PC使用，以后会有专门的PC组件，目前只能通过自己制作的方式。

**Comment by aoxiangsky** [comment]
> 

产品让抄飞鱼上的组件，头大啊

**Comment by aoxiangsky** [comment]
> 现在虽然专于移动端，但是大部分组件可以在PC使用，以后会有专门的PC组件，目前只能通过自己制作的方式。

产品让抄飞鱼上的组件，头大啊，能不能先开源几个oxz

**Comment by imouou** [comment]
飞鱼有自己的组件开发方式，你了解下文档的组件的定义方式，是可以做的。另外一个留意近期的网站新版，资源跟组件会重新组织，到时下载一个参考下，按这种方式定义的组件，PC移动都能通用。
