### ISSUE TITLE
不使用命令行工具生成项目，如何配置跨域

### ISSUE THREAD

**Issue by LYXCQX** [imouou/BUI-Guide#25]
不使用命令行工具生成项目，如何配置跨域，有办法使用原生等插件么

**Comment by LYXCQX** [comment]
我多页面开发使用 bui.ready 以后发现他要跳转 main.html 这个可以配置么

**Comment by imouou** [comment]
多页开发没有指定要跳转 main.html, 每个都是独立的页面, 跟web 开发是一致的, 单页才需要指定

**Comment by LYXCQX** [comment]
您好，我第一次使用这种单页模式的开发，能简单讲解一下，这种方式有什么好处么，谢谢了

**Comment by imouou** [comment]
> 您好，我第一次使用这种单页模式的开发，能简单讲解一下，这种方式有什么好处么，谢谢了

这个请查看文档吧, 文档上面的好处都有说明 http://www.easybui.com/docs/

**Comment by LYXCQX** [comment]
好的谢谢
