### ISSUE TITLE
同一个接口多次加载的问题

### ISSUE THREAD

**Issue by LYXCQX** [imouou/BUI-Guide#26]
首页加载进来，获取轮播图，同一个接口连续加载了四次，请问一下怎么闭环这个问题 
if( !uiSlide ){
           // 初始化焦点图
            bui.ajax({
                url : apiUrl+"reqinfo",
                data : {}, //接口请求的参数
                // 可选参数
                method : "GET"
            }).then(function(result) {
                // 初始化
                uiSlide = bui.slide({
                    id : "#tabSlideImg",
                    height : 250,
                    autopage : true, //分页
                    loop : true, //
                    autoplay : true, //自动播放
                    interval : 2000, //滚动时间
                    template : function() {
                        var html ='<div class="bui-slide-main"><ul>"';
                        $.each(result.dataList,function(index, ad) {
                            if(ad.adType == 0){
                                html +='<li><img src="'+ad.adImg+'" alt=""></li>';
                            }
                        });
                        html+="</ul></div>";
                        return html;
                    },
                })
            });
        }

**Comment by imouou** [comment]
这个你要看你的代码为何请求了4次吧, 示例代码是请求一次

**Comment by LYXCQX** [comment]
![vp 02 p7eibmh igjlosus](https://user-images.githubusercontent.com/44891636/48602330-c2b42500-e9ad-11e8-80f0-a906ff831a97.png)

你好我这个是按照工具生成的项目来的，我看我没有修改的地方有的也请求了好几次

**Comment by imouou** [comment]
那些是工程里面同步刷新用到的东西, 实际你部署或者的是独立的一个文件夹, 这个是调试环境

**Comment by LYXCQX** [comment]
我看了一下，到达后台的请求是有两次的，您的意思是这个是调试环境的原因么，等部署到正式就没有这么多次了，还是说我要做什么响应的配置

**Comment by imouou** [comment]
你下载官网的demo 去试试看会不会

**Comment by LYXCQX** [comment]
也是一样的，我这个每次都加载了两次

**Comment by LYXCQX** [comment]
我就是用buijs命令行工具生成的项目

**Comment by imouou** [comment]
你这个情况应该跟TAB一起使用有关, 
第1个,  loader.require("moduleName")  第一次加载,有方法执行就会执行一次
第2个, loader.require("moduleName",function(){}) 有回调的时候, 就会每次调用这个回调, 这样就变成了2次, 所以你可以去掉第一个的自执行, 或者在第2个加个状态来区分这2种执行的时机
