### ISSUE TITLE
页面跳转后 数据重载问题

### ISSUE THREAD

**Issue by raisew** [imouou/BUI-Guide#28]
从一个页面跳到登录页面，登录成功后跳回来，数据都没有加载，用router.load 和 bui.load 都没有数据，没有执行到js里面的方法

**Comment by imouou** [comment]
单页的模块加载以后默认是缓存的, 页面也是一样, 你后退不做操作并不会执行任何事情, 你需要了解官网专栏里的 微信变态路由, 里面有各种路由的操作处理. http://www.easybui.com/guide/#/article
