### ISSUE TITLE
底部导航反复点击A-B跳转 ，会出现A页面的数据追加显示在B页面数据下面

### ISSUE THREAD

**Issue by Fern123** [imouou/BUI-Guide#29]
![image](https://user-images.githubusercontent.com/35794656/49557817-dbc44c00-f943-11e8-9944-9f5240f741da.png)
上图是我底部导航代码，在跳转页面也执行了 pageview.init（）=function（）{} 去执行数据重新请求，代码如下：
![image](https://user-images.githubusercontent.com/35794656/49558018-93595e00-f944-11e8-970a-9e0f1208225b.png)
我也试过将window.loader = bui.loader({ cache: false});放在index.js页面中，但是运行会提示main.html 404，请问是我放置的位置有问题吗？我要怎么做才能解决这个问题

**Comment by imouou** [comment]
loader.require("pages/home") 默认加载模块的时候, page.init 有执行的话, 就会触发一次, 然后缓存下来. 这时候,只触发一次. 
loader.require("pages/home", function(home){ home.init() })  这里有回调的时候, 每次都会触发, 也就变成了2次, 这个问题取决于你对这个模块的理解, 你可以 home.js 那里不要执行, 这样通过tab 就每次都只执行一次.    如果你这个home.js 的模块, 还是独立的一个模块, 那就代表, 你的page.init 是默认必须执行的, 那你可以通过状态去区分是tab 调用, 还是路由直接跳转, 这样讲可以理解吗?

**Comment by Fern123** [comment]
我没明白o(╥﹏╥)o  。底部导航的这几个模块我的期望是每次点击进入都要进行一次数据刷新，而且这几个模块也只能通过底部导航栏一个入口进入。tab.on 默认加载得是第0个模块，也就是刚打开页面会执行第0个模块的init方法，我没有在其他地方调用loder.require（“pages/home”）,怎么会变成了两次加再呢？而且 我不想缓存这个加载的数据，我加上了window.loader = bui.loader({ cache: false});，也没有解决这个问题
![image](https://user-images.githubusercontent.com/35794656/49567584-21dfd680-f969-11e8-9360-69486559ffd3.png)

**Comment by Fern123** [comment]
1.这是我第一次进入C模块时候列表显示
![image](https://user-images.githubusercontent.com/35794656/49567669-594e8300-f969-11e8-8a98-8f801bd99e5f.png)
2.我点击了B模块 ，之后再点击C模块就成了这个样子，黄框中是B的数据列表
![image](https://user-images.githubusercontent.com/35794656/49567827-d679f800-f969-11e8-8291-e80fa6b03d0e.png)

**Comment by imouou** [comment]
首先, 排查 B模块的 list 控件跟 C模块的list 控件是不是相同ID, 第2, bui.list 提取到 pageview.init 外面执行, 只需要初始化一次, 不用每次调用 pageview.init 生成, 你需要的是, 把 uiList 这个实例,挂载在 pageview.list 上, 这样, 你就可以在 每次 to 跳转的时候, 加载该模块实例的刷新方法 module.list.refresh() ;

**Comment by imouou** [comment]
你这样挂载也没问题, 不过最好起个比较好理解的名字,  另外因为第一次加载的时候会初始化list, 还会调用 mod.list 来触发刷新, 那你不是可以给个状态, 如果还没初始化, 就不调用 mod.list 吗

**Comment by imouou** [comment]
理解了这个模块化的加载以后, 就能很自由灵活的处理各个模块之间的依赖了.

**Comment by Fern123** [comment]
是啊，谢谢，顿时明朗多了(*￣︶￣)
