### ISSUE TITLE
请问css的class样式在android手机浏览器和接入的微信上都不显示，ios和web浏览器都很正常，怎么整？

### ISSUE THREAD

**Issue by Fern123** [imouou/BUI-Guide#31]
![image](https://user-images.githubusercontent.com/35794656/49631034-7fd4f280-fa2b-11e8-8be9-9f30b2e5ccb4.png)
![image](https://user-images.githubusercontent.com/35794656/49631053-8f543b80-fa2b-11e8-9adf-4610e0fb9488.png)
![image](https://user-images.githubusercontent.com/35794656/49631189-0ab5ed00-fa2c-11e8-938c-e7838131ff72.png)

但是写在标签内的style就是有效的

**Comment by imouou** [comment]
排查下你的样式是否有乱码导致无法解析吧, 这个不会不解析的. 安卓ios跟chrome模拟几乎是一致的.

**Comment by imouou** [comment]
ok
