### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by xmVu** [imouou/BUI-Guide#38]
events.js:183
throw er; // Unhandled 'error' event
^
Error: ϵͳ�Ҳ���ָ����·����

at notFoundError (D:\code\demo\node_modules\cross-spawn\lib\enoent.js:11:11)
at verifyENOENT (D:\code\demo\node_modules\cross-spawn\lib\enoent.js:46:16)
at ChildProcess.cp.emit (D:\code\demo\node_modules\cross-spawn\lib\enoent.js:33:19)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: gulp dev
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2018-12-14T01_01_29_677Z-debug.log

---------------------------log 文件内容-----------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ 'D:\download\node\node.exe',
1 verbose cli 'D:\download\node\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'run',
1 verbose cli 'dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: D:\download\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\code\demo\node_modules.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;D:\download\node;D:\download\tortoiseGit\bin;D:\download\Git\cmd;C:\Go\bin;C:\Users\Administrator\AppData\Roaming\npm;%GOPATH%\bin
9 verbose lifecycle @~dev: CWD: D:\code\demo
10 silly lifecycle @~dev: Args: [ '/d /s /c', 'gulp dev' ]
11 silly lifecycle @~dev: Returned: code: 1 signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: gulp dev
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (D:\download\node\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack at emitTwo (events.js:126:13)
13 verbose stack at EventEmitter.emit (events.js:214:7)
13 verbose stack at ChildProcess. (D:\download\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack at emitTwo (events.js:126:13)
13 verbose stack at ChildProcess.emit (events.js:214:7)
13 verbose stack at maybeClose (internal/child_process.js:925:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd D:\code\demo
16 verbose Windows_NT 6.3.9600
17 verbose argv "D:\download\node\node.exe" "D:\download\node\node_modules\npm\bin\npm-cli.js" "run" "dev"
18 verbose node v8.11.1
19 verbose npm v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: gulp dev
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by xmVu** [comment]
重新走一遍创建流程

**Comment by imouou** [comment]
查看下node 的版本? 重新安装看看
