### ISSUE TITLE
开发包

### ISSUE THREAD

**Issue by Jony1943** [imouou/BUI-Guide#4]
官网教程里面的下载开发包，单页开发包和多页开发包的下载地址，是不是写反了？

**Comment by imouou** [comment]
谢谢反馈, 经确认, 没有写反, 单页开发包里面是整个工程, 删除 platforms, templates 目录就可以了, 这是为了确保你下载的是最新的单页开发版本. 当然如果你使用buijs 命令行创建, 就不用管这个了.  多页开发包里面虽然也是首页, 但是 index.js 的初始化方式是没有初始化路由的.

**Comment by imouou** [comment]
有问题及时沟通就好.^^
