### ISSUE TITLE
        <header class="bui-bar>的问题

### ISSUE THREAD

**Issue by yeziWee** [imouou/BUI-Guide#40]
<header class="bui-bar>无法对其设置box-shadow,设置了会无效

**Comment by yeziWee** [comment]
<header class="bui-bar>无法设置阴影,虽然能设置上去,但是页面呈现是没有效果的

**Comment by imouou** [comment]
这种你要把 header 变成定位才有这种层级概念, 但一般不建议使用阴影, 到导致移动动画过程性能损耗过多
