### ISSUE TITLE
在模块定义中，怎么验证用户并跳转到登录页

### ISSUE THREAD

**Issue by Steven0621** [imouou/BUI-Guide#44]
![image](https://user-images.githubusercontent.com/6915294/51153576-b3692f00-18ab-11e9-9f01-4241246f4e92.png)

**Comment by Steven0621** [comment]
这样直接跳转，就没办法输出模块了，在back方法的回调函数中，引用模块方法提示错误？大神怎么搞啊？

**Comment by imouou** [comment]
你可以把登录模块做成公共弹窗形式, 不论在哪里,没登录都会弹出弹窗让用户登录就好, 或者等新版看看是不是还有这个问题.

**Comment by Steven0621** [comment]
好的，非常感谢！

**Comment by hy3225569** [comment]
大神！具体是怎么弄得？
