### ISSUE TITLE
图片压缩修正后(已得到blob数据) 如何替换上传的文件数据

### ISSUE THREAD

**Issue by Abelies** [imouou/BUI-Guide#45]
function formUpData(blobFiles){
console.log('before', uiUpload3.data()[uiUpload3.data().length-1])
console.log('before', URL.createObjectURL(uiUpload3.data()[uiUpload3.data().length-1].data))
                uiUpload3.data()[uiUpload3.data().length-1].data = blobFiles;
console.log('after', uiUpload3.data()[uiUpload3.data().length-1])
console.log('after', URL.createObjectURL(uiUpload3.data()[uiUpload3.data().length-1].data))

                uiUpload3.start({
                    url: localStorage.post + "drivermanger-server/api/driver/file/avatar",
                    headers: { token: sessionStorage.token },
                    onSuccess:function (data) {}

**Comment by imouou** [comment]
uiUpload3.start({
                url: localStorage.post + "drivermanger-server/api/driver/file/avatar",
                data: { file: 替换后的数据 },
                onSuccess:function (data) {}

**Comment by Abelies** [comment]
> uiUpload3.start({
> url: localStorage.post + "drivermanger-server/api/driver/file/avatar",
> data: { file: 替换后的数据 },
> onSuccess:function (data) {}



> data: { file: 替换后的数据 },

这样上传的依然是uiUpload3.data()里最后个file  并不是压缩后的

**Comment by imouou** [comment]
你没有更新成最新版吧?

**Comment by Abelies** [comment]
> 你没有更新成最新版吧?

v1.5啊   通过改源码解决了   谢谢回答
function c(e) {
                var n = t.extend(!0, {},
                C, e);
                if (x = n.url, y = m.value(), O = n.showProgress, y) {
                    if (O && v.show(), j) {
                        var i = n.data,
                        a = new FormData;
                        a.append(n.fileKey, y);
                        for (var o in i) a.append(o, i[o]);
                        if ( !i ) { n.data = a };
                        // n.data = a,
                        d(n)
                    } else w.start(n);
                    return this
                }
            }

**Comment by imouou** [comment]
最新版是 1.5.1 , 不建议修改源码的方式, 下次有问题你还敢更新吗?
