### ISSUE TITLE
buijs单页面开发包最新版npm run dev之后不能热更新，必须npm run build之后dist文件夹里的文件才能跟src同步

### ISSUE THREAD

**Issue by html546** [imouou/BUI-Guide#48]
buijs单页面开发包最新版npm run dev之后不能热更新，必须npm run build之后dist文件夹里的文件才能跟src同步,这个地方我这边试了是必须npm run build之后才能更新，如果不npm run build的话，修改不生效。能给看看吗

**Comment by imouou** [comment]
不能有中文路径,否则热更新会失效, 热更新只针对scss, html,js 那些是整页刷新
