### ISSUE TITLE
升级到最新版本，bui.confirm点击了确定后，没反应，不能关闭了。

### ISSUE THREAD

**Issue by Steven0621** [imouou/BUI-Guide#51]
升级到最新版本，bui.confirm点击了确定后，没反应，不能关闭了。

**Comment by Steven0621** [comment]
![image](https://user-images.githubusercontent.com/6915294/52773325-a17ad780-3075-11e9-8859-f65d17060ccf.png)

**Comment by imouou** [comment]
因为默认的autoClose 关闭了, 可以使用 https://unpkg.com/buijs/lib/latest/bui.js 改成 0.6.0 获取最新的bui.js 版本, 这个版本恢复了之前的默认配置, 或者全局配置下 bui.config.confirm = { autoClose: true }

**Comment by Steven0621** [comment]
好的，谢谢！
