### ISSUE TITLE
Tab切换页面模板中页面不能自动匹配高度，差不多只显示到一半位置

### ISSUE THREAD

**Issue by akaryqin** [imouou/BUI-Guide#54]
就是直接使用下载下来的多页tab模板，然后把跳转的页面更换成同样下载下来的列表页面模板（例如把列表模板直接改文件名成“home.html”），显示的效果是列表部分不能自动扩展到全部高度。这是什么原因？

**Comment by imouou** [comment]
tab 动态加载的时候, 除了 html 模板, 还有一个模块的初始化加载, 查看这个脚本有没有正确加载

**Comment by akaryqin** [comment]
我把main.js中tab对象从bui.slide更改成bui.tab后正常了。
有点忘了这个bui.slide是旧版本就是这样，还是我更改成bui.slide了。。。。
非常感谢大佬的指导，资料还是比较少，好多使用方法都需要反复摸索。

**Comment by imouou** [comment]
你需要的是从 buijs create -t main-tab 这样创建一个干净的工程使用, 多用工具, 工具保持最新的写法, 像, buijs , bui-fast 插件都是为了减少这种书写的坑. 你可以查看 www.easybui.com 官网的文档, 里面有各种你需要的信息.
