### ISSUE TITLE
请问，当点击交互列表的每一项的li的时候，为什么li的高度总会改变

### ISSUE THREAD

**Issue by mc210904** [imouou/BUI-Guide#57]

**Comment by imouou** [comment]
你查看你的模拟设备的缩放比例是不是100%, 非100% 页面的缩放是会有误差

**Comment by mc210904** [comment]
是点击li的时候，li的高度变成了另外一个固定的值，不是原来的值了，这跟缩放没有关系吧

**Comment by imouou** [comment]
可以查看我们官网的示例demo, 以这个示例的效果为准 http://www.easybui.com/demo/#pages/ui _controls/bui.listview

**Comment by mc210904** [comment]
想改成自己想要的样式都不行吗，一定要按照demo吗，那局限性就太大了

**Comment by imouou** [comment]
每个控件有每个控件的实现方式, 你可以根据已有结构去参考实现你的样式, 结构上肯定不能随意更改的
