### ISSUE TITLE
关于bui.tab

### ISSUE THREAD

**Issue by jutaos** [imouou/BUI-Guide#59]
js里使用bui.tab时会报错：
Uncaught TypeError: bui.tab is not a function
    at test:61
    at bui.js:24
    at HTMLDocument.<anonymous> (zepto.js:453)
(anonymous) @ test:61
(anonymous) @ bui.js:24
(anonymous) @ zepto.js:453

**Comment by imouou** [comment]
你的bui版本太低, 请使用 buijs create 创建工程, 那样拿到的才是最新的工程, 案例有部分还是基于旧版制作, 仅供学习.
