### ISSUE TITLE
BUI可以使用手机上的硬件设备么？例如使用蓝牙通讯

### ISSUE THREAD

**Issue by akaryqin** [imouou/BUI-Guide#60]
如题，没有发现怎么使用BUI访问硬件设备。
目前，我需要通过蓝牙与另外的蓝牙设备进行数据通讯，
不知道怎么去做。之后也有可能使用其它硬件设备，应该怎么做？
另外，还有个问题，应该怎么嵌入地图？例如百度地图？

**Comment by imouou** [comment]
地图按普通页面开发引入就行, 蓝牙,扫码等硬件设备, 你需要用什么打包, 就用该平台的API去使用, BUI只是提供一个界面交互的UI框架, 不涉及原生.
