### ISSUE TITLE
表单填写页面，左侧标题如何加大宽度

### ISSUE THREAD

**Issue by akaryqin** [imouou/BUI-Guide#61]
可能是个简单问题，可能只是没找到方法，又来麻烦您了。
我在使用表单页面填写或显示内容时，每一行都是左侧是标题，右侧是输入控件或显示控件。例子中左侧标题部分都是使用bui-label，但我看最多是正好显示5个汉字。我现在需要显示7个左右的汉字，这样就会换行显示了，怎么才能稍稍加长一些宽度，可以一行显示出来，不用换行？
我试过使用label标签，这样的话会占用一行的一半位置，左侧占用就又多了，留给右侧显示内容的空间就又不够了。麻烦您给指导一下，谢谢。

**Comment by imouou** [comment]
给当前页面的 .bui-label {width:2rem} 加个合适的宽度就好

**Comment by akaryqin** [comment]
多谢，右侧只显示文本（bui-value标签）的时候，怎么向右对齐？我试过bui-align-right没起作用。

**Comment by imouou** [comment]
bui-value 默认是 display:inline-block; 改成block 就会有效, 这些是css 基础, 请自行百度查阅.

**Comment by akaryqin** [comment]
不好意思，我初学web的内容，麻烦您了。
在哪里可以查看bui这些标签的标签封装的内容么？bui的js文件中很难找到实际有用的内容。
没经过处理的js文件有哪里可以下载么？

**Comment by imouou** [comment]
其实你需要的是理解css , 这个js 最终出来的是结构跟样式, 理解了这个自然就知道怎么去修改, 建议可以从盒子模型开始了解, BUI的CSS文档里面其实没有多少要记的, 学会布局跟快速生成就行, 常用的都在样式规范里面.

**Comment by akaryqin** [comment]
好的，多谢指导。
