### ISSUE TITLE
关于动态加载纵向选项卡

### ISSUE THREAD

**Issue by H-Dreamland** [imouou/BUI-Guide#62]
正在做一个动态加载纵向选项卡 ，按照文档上的写法却无法触发点击效果切换选项卡。  请问是有什么需要注意的吗。

**Comment by imouou** [comment]
buijs create -t main-tab  创建这个工程参考一下就知道了, 理解了这个工程, 就可以理解纵向选项卡, 它跟这个例子 http://www.easybui.com/demo/source.html?url=pages/ui_controls/bui.tab_side&code=html,js,result, 只是初始化的时候多了一个 autoload 参数, 并且tab上面多了一个 href 地址,指向某个模块.

**Comment by H-Dreamland** [comment]
但是我的这部分并不是跳转到另一个页面或模块，而是在js里动态拼接了HTML代码
![image](https://user-images.githubusercontent.com/21021225/54889849-94a59b00-4ee1-11e9-997f-5c9e13335c27.png)`
if( !tab ){
        // 初始化侧边分类, 商家分类及内容较少时,无需开启异步加载
        tab = bui.tab({
            id: "#tabSide",
            menu: "#tabSideNav",
            width: tabWidth,
            direction: "y",
            animate: false,
            autoload: true,
        })

      }
    }
    

    bui.ajax({
        url: apiUrl+"/goods/getAllCategory",
        data: {},//接口请求的参数
    }).then(function(result){
        var categoryHtml = "";
        var liHtml = "";
        result.data.map(function (cateforyItem, index) {
            categoryHtml+=`<li class="bui-btn">${cateforyItem.title}</li>`;
            liHtml += `<li ${(index == 0) ? '' : 'style="display: none;"'}>
                        ${cateforyItem.goodsList.map((goodsItem,goodsIndex)=>`
                        <ul class="bui-list bui-list-thumbnail" >
                            <li class="bui-btn bui-box clearactive" href="pages/item/detail.html" param='{"id":${goodsItem.id}}'>
                                <div class="bui-thumbnail" href="pages/item/detail.html" param='{"id":${goodsItem.id}}'><img src="images/pro05.png" alt=""></div>
                                <div class="span1">
                                    <h3 class="item-title">${goodsItem.title}</h3>
                                    <p class="item-text line-limit-length">${goodsItem.descriptionContent}</p>
                                    <div class="bui-box">
                                    <div class="price"><i>￥</i>${goodsItem.presentPrice}</div>
                                </div>
                                </div>
                            </li>
                        </ul>`).join('') }
                    </li>`
        });
        $("#tabSideNav").html(categoryHtml);
        $("#tabSide").html(liHtml);
        
    },function(result,status){
        // 失败 console.log(status)
    });
`
目前的效果是这样
![image](https://user-images.githubusercontent.com/21021225/54890617-295dc800-4ee5-11e9-82ce-5f3fc7b2c2cb.png)

**Comment by imouou** [comment]
你这种是请求以后自己渲染, autoload 声明为true 以后, 你要告诉控件加载哪个页面, href 这个属性, 加载的就是模板, 模块里面处理对应的模块,  http://www.easybui.com/demo/#pages/ui_controls/bui.tab_dynamic 这个就是异步加载的例子
