### ISSUE TITLE
我想问下bui官网更新后，怎么看之前官网的demo

### ISSUE THREAD

**Issue by yukaihappy** [imouou/BUI-Guide#66]
我想问下bui官网更新后，怎么看之前官网的demo

**Comment by imouou** [comment]
官网更新并不影响demo的，在首页或者在域名后面加上demo .  http://www.easybui.com/demo/

**Comment by yukaihappy** [comment]
你好呀，我想访问原先的http://www.builive.com/，我记得那个网站可以选择前端和后端入口的来着，我该怎么访问呢？

在 2019-04-07 22:09:00，"王小o" <notifications@github.com> 写道：


官网更新并不影响demo的，在首页或者在域名后面加上demo . http://www.easybui.com/demo/

**Comment by imouou** [comment]
这两个是不同的框架，我们也不清楚的
