### ISSUE TITLE
BUI 存储的初始化问题

### ISSUE THREAD

**Issue by mengshixu** [imouou/BUI-Guide#67]
我使用了单页路由的开发模式，当页面启动时需要初始化存储，在初始化存储的时候需要指定存储的data内容，这时候初始化存储会不会覆盖已经保存在本地的数据，我想问一下，我通过什么方式可以在初始化存储之前也能读取到已经保存过的数据，比如我通过存储保存了用户的session，我想在页面第一次启动的时候检查session是否存在，去服务器验证是否有效，根据结果再去初始化存储。

**Comment by imouou** [comment]
实际上这个跟用什么开发方式没有必要联系, 这个数据存储在 bui.ready 都可以获取得到, 另外路由里面有个 beforeLoad 在每次页面跳转前都会执行.
