### ISSUE TITLE
如何在BUI.ready外调用组件方法

### ISSUE THREAD

**Issue by a670977541** [imouou/BUI-Guide#69]
组件的初始化都是在BUI.READY中初始化，在BUI.READY调用组件的方法也可以，那如何在BUI.READY外调用组件的方法

**Comment by imouou** [comment]
所有组件都应该在 bui.ready 里面执行, 才能确保加载的时机是正确的. 正常也不需要关注何时在外部调用

**Comment by a670977541** [comment]
> 所有组件都应该在 bui.ready 里面执行, 才能确保加载的时机是正确的. 正常也不需要关注何时在外部调用

谢谢你的回答，我现在是个学生，在用BUI做个项目。我说的意思是，比如uiDialogDown.open();这个方法，我想在bui.ready外的一个function中调用这个方法该怎么弄。还是说这样不应该这样做，得在bui.ready中调用这个方法才比较合适。谢谢

**Comment by imouou** [comment]
把 var uiDialogDown 声明在 bui.ready 外部.

**Comment by a670977541** [comment]
谢谢，明白了，中午麻烦你了
