### ISSUE TITLE
打包后手机的部分页面返回键会直接导致退出应用？如何解决

### ISSUE THREAD

**Issue by zhangsiyuan1995** [imouou/BUI-Guide#70]

**Comment by imouou** [comment]
打包后的应用取决于你打包的平台, 打包平台会提供劫持物理按键的操作, 然后使用后退就行, 再简单点, 用命令行 buijs create -p dcloud 创建对应的平台工程, 把index.js 的注释去掉, 就会有对应的物理后退处理.

**Comment by zhangsiyuan1995** [comment]
好的谢谢
