### ISSUE TITLE
bui中input无法触发change事件

### ISSUE THREAD

**Issue by ZdMirLong** [imouou/BUI-Guide#71]
页面中有个文本框,绑定了change事件;文本框扫码之后不触发change事件;设置扫码之后主动失去焦点,在失去焦点也无法触发

**Comment by imouou** [comment]
你这个触发的是原生扫码, 不一定会继续触发页面的change事件, 如果你的事件已经绑定在change, 用 trigger 在扫码结束后手动触发一次就可以了
