### ISSUE TITLE
同一个页面，多次使用router.loadPart局部加载模块，子模块无法接收参数

### ISSUE THREAD

**Issue by doscanner** [imouou/BUI-Guide#73]
同一个页面，多次使用router.loadPart局部加载模块，子模块接收的参数，始终是父页面第一次router.loadPart传入的参数

**Comment by imouou** [comment]
router.loadPart 接收参数是 router.getPartParams(id);  不是 router.getPageParams .
相同模块加载在相同ID, 不管父层传什么参数, 重新加载的时候都会拿到最后一次传的参数.

**Comment by bc20180808** [comment]
子页面没有接收不到传参啊 router.loadPart

**Comment by doscanner** [comment]
父页面：
router.loadPart({ id:"#part", url: "pages/page1/page1.html", param: {id:'1'} });
router.loadPart({ id:"#part2", url: "pages/page2/page2.html", param: {name:'2'} });

page1:
router.getPartParams().id //1

page2:
router.getPartParams().name //undefined

**Comment by imouou** [comment]
请参考 
加载局部模块
http://www.easybui.com/demo/#pages/router/loadPart/loadPart 
局部模块接收父层传参, 需要拿的是 part 或者 part2 的id 
http://www.easybui.com/demo/#pages/router/loadPart_part/loadPart_part

**Comment by doscanner** [comment]
谢谢，现在看明白了
