### ISSUE TITLE
关于页面返回的问题

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#75]
当前页面是B页面，从A页面进入的，B页面要继续跳转到C页面，但是希望回退一级后再跳转。
使用
```javascript
router.back({
    callback: function(){ router.load({ url: 'pages/page/c.html' }); }
});
```
的方式有一个切换到上一个页面的动效，使用`router.replace()`又没有跳转动画，怎么办？
（这样做的目的是为了使跳转层级不那么深，所以想到了这样的办法，不知道思路是否正确，请求指点！）

**Comment by imouou** [comment]
这样做其实没有必要, 对用户体验来讲也不好, 一个是用户记住了当前的操作是 A-B-C, 结果用户点击进入C页面反而有个后退的操作, 这是不好的. 控制路由的层级是指, 合理的前进后退, 比方你的路由应该像小程序一样, 从首页A到列表页B,再到详情页C, 可以认为是一个完整的路由加载了, 这个时候, 在C页面不要有其它链接, 可以继续进去到详情页了, 应该是由用户后退以后, 再从列表进去, 不知道这样讲能不能理解.

**Comment by shoppingzh** [comment]
理解了，谢谢！还有一个问题：如果路由层级过深会不会在比较老的机器上表现得十分卡顿？

**Comment by imouou** [comment]
卡顿并不是由路由层级过深导致的, 是内容过多或者内容渲染所耗的CPU或内存导致, 比方地图,图表, 这种即使是只有1层,在较老的机器都会卡顿, 这是webview不可避免的, 好在现在的机子性能还不错, 打包以后速度问题不大, 另外路由有一个 firstAnimate 参数, 专门处理跳转卡顿的问题, 为true 则是动画优先, 先处理页面跳转再进行渲染.

**Comment by shoppingzh** [comment]
好的，理解了，非常感谢。
