### ISSUE TITLE
微信返回前页面强制刷新问题

### ISSUE THREAD

**Issue by 18068280110** [imouou/BUI-Guide#8]
微信公众号里面返回上一个页面会强制刷新整个页面，bui框架中怎么做才能不刷新上一个页面？

**Comment by 18068280110** [comment]
官网上看到单页面路由创建工程是个app的例子。和想多页面路由那样，直接引入css js开发web网页该怎么做呢

**Comment by imouou** [comment]
请查看教程-->快速开始的教程, 默认就是多页的开发方式, 下载多页的工程就可以直接使用了

**Comment by 18068280110** [comment]
单页面有直接使用的方式吗？

**Comment by imouou** [comment]
单页需要配合BUI的路由跟模块化才能发挥优势.
