### ISSUE TITLE
input 框在ios上键盘输入,输入拼音时会将所有的字母显示上去?

### ISSUE THREAD

**Issue by WangJianShun** [imouou/BUI-Guide#82]
![微信图片_20190611092045](https://user-images.githubusercontent.com/36885478/59236785-39ef2600-8c2a-11e9-90d2-fc48694ffa29.jpg)

**Comment by imouou** [comment]
是不是有用的 bui.store ? 是的话, 初始化的时候, 改成这样 modelEvent: "change" ;

**Comment by WangJianShun** [comment]
> 是不是有用的 bui.store ? 是的话, 初始化的时候, 改成这样 modelEvent: "change" ;

解决了 谢谢
