### ISSUE TITLE
使用底部导航动态动态加载的时候,每个选项下的页面的头部不会固定在页面的顶部,页面向上滑动,头部也会跟随滑动?

### ISSUE THREAD

**Issue by WangJianShun** [imouou/BUI-Guide#83]

**Comment by WangJianShun** [comment]
并且每个导航页面下的跳转链接都会来连续跳转两次，我是根据而文档的日子写的 ，为什么会出现这种情况呢？

**Comment by imouou** [comment]
你的头部是否可以作为公共头部呢? 可以的话参考这个例子会比较简单点. http://www.easybui.com/demo/source.html?url=pages/ui_controls/bui.tab_dynamic&code=html,js,result  

如果不是公共头部查看这个例子: http://www.easybui.com/demo/#pages/ui_controls/bui.tab_alone.html 源码: 
http://www.easybui.com/demo/source.html?url=pages/ui_controls/bui.tab_alone&code=html,js,result
http://www.easybui.com/demo/source.html?url=pages/ui_controls/bui.tab_alone_page1&code=html,js,result
