### ISSUE TITLE
loadPart后父页面元素获取不到

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#84]
我在A页面中loadPart B页面，B页面的内容加载到A页面后，我想为部分加载的内容添加点击事件，于是在我在A页面js中声明了如下代码：
```javascript
pageview.bind = function(){
    router.$('.bui-page').on('click', '.activity', function(){
         //do something
    });
}
```
但是我发现事件非但没有绑定上去，在loadPart后，router.$('.bui-apge')这个元素都获取不到了（该元素是确定存在于A页面的）

**Comment by imouou** [comment]
你这个是定义了一个方法, bind 有没有执行? 事件委托在哪里都可以使用,没有问题, 但要注意事件重复绑定,  另外, 这个事件绑定放在B页面的模块会不会更好维护?

**Comment by shoppingzh** [comment]
bind有执行，之所以不放在B页面是因为点击事件取决于它的父级页面，重点不是事件没有绑定，我在loadPart后在A页面打印router.$('.bui-page')，发现没有获取到A页面所对应的page元素

**Comment by shoppingzh** [comment]
我对照着官网的例子来了一遍，目前测试得到的结果是：A页面load part B页面后，A页面再使用router.$()获取不到此页面的任何元素了

**Comment by imouou** [comment]
那你需要排查你的代码了, 写了个例子, 你自己参考下, http://www.easybui.com/demo/#pages/router/loadPart/loadPart   
点击局部加载成功以后, 点击后退下面的示例, 控制面板是有输出的.

**Comment by shoppingzh** [comment]
http://xpzheng.java.cdnjsp.org/bui_test/src/index.html

麻烦您看一下我的例子，这是刚刚下载的单页开发包修改的部分文件，希望您能帮忙分析一下，谢谢！

**Comment by imouou** [comment]
事件委托可以在A模块下就进行绑定, 无需等待模块加载后再绑定. 在模块加载以后, router.$ 指向了最新的模块信息, 这个是有问题的, 会在新版修复.

**Comment by shoppingzh** [comment]
谢谢您的耐心解答，非常感谢！
