### ISSUE TITLE
打包后的ajax请求地址不对

### ISSUE THREAD

**Issue by lkjtzsq** [imouou/BUI-Guide#85]
![image](https://user-images.githubusercontent.com/32919242/59347233-aeb78280-8d46-11e9-8880-9821d23cb5d8.png)
测试环境没问题，可是打包后线上环境报ajax请求地址的错误，正确的地址应该是http://qxb.test.com/api/meeting
以下是我的代理设置和ajax请求
![image](https://user-images.githubusercontent.com/32919242/59347340-fa6a2c00-8d46-11e9-9aea-e6774bef3106.png)
![image](https://user-images.githubusercontent.com/32919242/59347358-06ee8480-8d47-11e9-8d3c-a0e6abfc4afd.png)
麻烦问一下怎么解决？

**Comment by imouou** [comment]
正式环境就把地址配置在 apiUrl 就好啦, 打包没有跨域问题.

**Comment by lkjtzsq** [comment]
非常感谢，果然是这样，问题解决了。 @imouou
