### ISSUE TITLE
bui.store配合art-template的使用问题

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#87]
```
<script id="ff8f0755_d24a_4992_ab9d_f0d80a52e60f.art" type="text/html">
    {{if list && list.length}}
        {{each list obj index}}
            {{set profile = obj.profile || {} }}
            <div class="span2 bui-box-vertical user">
                {{if profile.avatar}}
                    <img class="avatar" src="{{$imports.virPath}}/blob?key={{profile.avatar}}&protocolCheck=true">
                {{else}}
                    <img class="avatar" src="images/student.png">
                {{/if}}
                <span class="name">{{profile.firstName}}</span>
            </div>
        {{/each}}
    {{else}}
        <div class="" style="text-align: center;padding: .35rem 0;">
            <i class="icons-nodata-b fonts-lx"></i> 暂无数据
        </div>
    {{/if}}
</script>
```
这是art-template的模板，当列表为空时显示暂无数据。
bui.store中定义了列表数组并且初始化值为一个空数组，页面在展示的时候最先展示的是一个提示“暂无数据”的空列表，而后在`mounted`回调中通过ajax获取了新的列表，通过list.$merge()函数合并之前的空列表和当前的新列表，然后页面再次渲染。
但是，第二次渲染后的内容是append到页面中的，导致新的列表数据与“暂无数据”提示同时出现，请问应该如何解决这个问题？

另外，如果我想追踪列表获取前到获取后的整个过程，在获取到数据前列表展示loading，获取到数据后替换loading，如果获取到的列表为空还要显示无内容提示信息，配合bui.store如何实现比较好？
（在没有使用bui.store前，我的做法是在模板的wrapper div中定义loading，这样页面一开始就显示加载中，然后获取后台数据后通过art-template就是上述的方式覆盖loading，如果有列表就展示列表，否则展示暂无数据友好提示。）

**Comment by imouou** [comment]
你需要的是一个 b-template 指向你的模板, 在你的模板里面操作这个判断, 用es6模板简单得很, 另外列表类的数据, 如果需要下拉刷新, 直接使用 bui.list 的初始化就行, 不需要跟 bui.store 一起使用, 那样意义不大.

**Comment by imouou** [comment]
你在 mounted 里面把请求数据前使用loading, 请求后把值赋给 模板的数据的时候, 把loading关闭就好, 数据的渲染很快, 没必要在它的数据渲染后才执行关闭loading

**Comment by shoppingzh** [comment]
我截取一下我的代码吧：
```
<div class="bui-fluid users" b-template="page.studentList(page.unCommentList)"></div>
```
您可能没太理解我的意思，我说的意思是第一次的空列表会渲染一次，渲染结果是暂无数据空列表。
而后，通过ajax请求的数据覆盖原有空列表，页面再次渲染时，将新的列表append到了上一次渲染的结果后，而我想要的结果是直接覆盖，请问这里需要如何处理？

大佬，您的文档我都有细看，我的列表不是分页列表，而且您也建议在单页应用中不一定非得使用store，但是我目前这个场景我觉得很适合使用store处理，所以我就用了。

**Comment by imouou** [comment]
给 b-template  加多一个 b-command="html"

**Comment by shoppingzh** [comment]
这个我之前就已经试过了，不行，文档中说的是b-command只会对第一次渲染起作用。。。

**Comment by imouou** [comment]
b-command="html"  你要覆盖的数据就不能使用合并的方法啦  list.$replace()

**Comment by shoppingzh** [comment]
豁然开朗！之前也在想是这个bui.array的方法调用问题，但是通览一遍bui.array的api后发现没有直接覆盖的函数，就使用了merge，原来是自己粗心了没有看到replace函数。。。。
谢谢啦。

**Comment by shoppingzh** [comment]
好吧，问题仍然没有得到解决，第一次渲染的内容仍然没有被覆盖。。

**Comment by imouou** [comment]
等cdn 的脚本更新为1.5.4, 替换成最新的就好,  https://cdn.jsdelivr.net/npm/buijs/lib/latest/bui.js

**Comment by shoppingzh** [comment]
好的

**Comment by imouou** [comment]
用这个 https://cdn.jsdelivr.net/npm/buijs@0.7.0/lib/latest/bui.js

**Comment by shoppingzh** [comment]
好的，谢谢！
