### ISSUE TITLE
怎么样实现用户未登录跳转到指定模块

### ISSUE THREAD

**Issue by hy3225569** [imouou/BUI-Guide#88]
单页开发中，我使用了main_tab模板，在main.js 初始化函数中写了router.load({url: "pages/login/login.html"})这行代码，表示未登录时跳转到登陆页面，可再我点击登录后<div class="bui-btn round primary" href="pages/main/main.html">登录</div>再跳转到main.html底部动态加载选项卡的功能却失效了。

**Comment by imouou** [comment]
先看文档的单页路由,模块,以及路由的加载原理, 理解了再使用, BUI里面加载过的页面推荐使用后退处理, 你登录的时候使用后退就行.

**Comment by hy3225569** [comment]
> 先看文档的单页路由,模块,以及路由的加载原理, 理解了再使用, BUI里面加载过的页面推荐使用后退处理, 你登录的时候使用后退就行.

好的  感谢! 解决了我的问题！
