### ISSUE TITLE
BUI页面跳转失效

### ISSUE THREAD

**Issue by lkjtzsq** [imouou/BUI-Guide#89]
![image](https://user-images.githubusercontent.com/32919242/59757990-820fe780-92bf-11e9-8d7c-7f68d6487a58.png)
1.问一下，为什么这么写跳转，有时候跳不出去，闪一下又跳回本页面了；
2.使用bui.back()，有时候也会失效；
3.A页面进入B页面，从B页面点使用rouer.loade()函数写的回退按钮点击时候是从左向右滑动的效果，我想要从右向左滑动怎么搞？

**Comment by imouou** [comment]
1. 这么写一定可以跳过去，但要明白main 跟这个pages/main/main页面有什么区别;
2. 没有问题，页面没有刷新都可以后退;
3. 不允许这么处理，加载过的使用后退就行，这个路由前进后退不应该捣乱视觉交互，另外可以使用dialog模拟一个公共登录，这样你可以自己控制进场效果

**Comment by lkjtzsq** [comment]
谢谢
