### ISSUE TITLE
打开路由属性hash: true，后退按钮失效。

### ISSUE THREAD

**Issue by efree0306** [imouou/BUI-Guide#90]
打开路由属性hash: true，在微信浏览器中后退按钮失效，在其他浏览器下正常，查找问题过程中代码几乎删光，可以确认的是，如果hash:false，后退按钮就可用，true就完全失效。

**Comment by imouou** [comment]
试试官方的例子在微信的效果, 默认就是在 hash:true . 
http://www.easybui.com/demo/ 
http://www.easybui.com/demo/index.js

**Comment by efree0306** [comment]
谢谢。解决这个问题陆续有一月有余，官网例子也测试过，官网正常，但是不知道为什么在我的程序里，却不行，和iis有关吗？查看过bui.js并没有太多线索，因为只是一个属性，解决起来无从下手。

**Comment by imouou** [comment]
录个视频看看, 这样没能明白你说的问题是什么, 官网路由正常说明在微信也是可以支持的. hash就是专门为了处理跳转第三方以后的返回回来的处理.

**Comment by efree0306** [comment]
视频太大，所以放在百度网盘上了。
链接: https://pan.baidu.com/s/1OXnV53TcahLWqupSkyFyOQ 提取码: tamd 
现象：hash：false,路由正常，返回按钮正常，只是不能跳转到外部链接，否则路由就乱了。
hash:true，tab按钮可以正常，返回按钮失效。

**Comment by efree0306** [comment]
不知道是否已看过视频，这个问题困扰有1月多久，仍旧没有头绪，有劳帮忙分析下原因，或是给个思路。感谢。

**Comment by imouou** [comment]
你的这个缺少测试环境, 可以使用你现在的方式就行, reloadCache 是最早用来解决这种后退问题而来.
