### ISSUE TITLE
关于bui_tab加载模块的问题

### ISSUE THREAD

**Issue by hy3225569** [imouou/BUI-Guide#91]
uiTab.on("to", function (index) {
        var left = $("#nav li")[index].offsetLeft;
        document.getElementById("uiNavbar").scrollLeft = left;
        switch (index) {
            case 0:
                bui.require(["pages/project/project-list"], function (mod) {
                    mod.init();
                });
                break;
            case 1:
                bui.require(["pages/project/project-list"], function (mod) {
                    mod.init();
                });
                break;
        }
    }).to(0);
以上，如果加载的的模块一样的话，因为模块不会冲重复初始化，因此导致我点击第二个tab时没有显示内容，有什么解决方案吗？

**Comment by imouou** [comment]
导致点击第二个tab时, 没有显示内容, 不是因为模块不会重复初始化, 因为你是有回调的, 你试试在 project-list 的init 方法里面输出一下, 切换的时候是不是有执行到里面去.  你的这个问题是你想把 list 公共抽取出来, 通过外部的调用, 初始化一个list ,  你可以试试, 调用  mod.init({id: "#tab1"})  这个id 的内容是在 bui-tab-main>ul>li 给 li 一个id, 代表内容加载到这里面去,  你的 project-list 模块里面,  list 的初始化的时候, 使用 传进来的 bui.list({id: "#tab1 .bui-scroll" })  这样去初始化, 你的列表就是都是独立的, 而参数是由你外层传进去的.

**Comment by hy3225569** [comment]
ok 谢谢大牛
