### ISSUE TITLE
在使用了底部bui-tab后，页面中b-click绑定事件会执行两次

### ISSUE THREAD

**Issue by southmaple** [imouou/BUI-Guide#92]
![企业微信截图_15621376073718](https://user-images.githubusercontent.com/41667239/60570447-302d8e00-9da4-11e9-97f5-1f3de0d8a0df.png)

![企业微信截图_15621366618763](https://user-images.githubusercontent.com/41667239/60569439-fc516900-9da1-11e9-8e1e-606b3a38a8b5.png)
![企业微信截图_156213737322](https://user-images.githubusercontent.com/41667239/60570210-a7aeed80-9da3-11e9-8f9f-ea57d9101c09.png)
![企业微信截图_15621374599249](https://user-images.githubusercontent.com/41667239/60570291-da58e600-9da3-11e9-9dbd-a421d6e04f8c.png)

**Comment by imouou** [comment]
在方法里面执行一次 event.stopPropagation();
