### ISSUE TITLE
bui.ajax 在 get 请求时获取不到参数

### ISSUE THREAD

**Issue by 5ini99** [imouou/BUI-Guide#93]
在 apicloud 环境中使用 bui.ajax 的原生模式时，用 get 模式请求无法获取 options 中配置的 data 参数，post 时正常，在 h5 网页模式中正常

**Comment by imouou** [comment]
默认无需使用原生模式, 正常使用 bui.ajax 就行, 打包的时候没有跨域问题.  另外 get 无法获取的话, 可以和后端排查, 可能某个类型没有设置, 原生的请求跟 $.ajax 是会有些许区别的, 具体需要排查.

**Comment by 5ini99** [comment]
@imouou 如果不用原生模式的话会有跨域问题，而且我用抓包看了数据提交的网络请求里确实没有参数，如果有时间的话排查一下吧，我没源码查起来费劲，现在我是把参数拼在 url 里正常了

**Comment by imouou** [comment]
APICloud平台确实是打包有跨域问题, 需要提供外网接口才能排查, 你也可以试试你用apicloud的请求是怎样能够成功

**Comment by 5ini99** [comment]
这是测试结果
![WX20190704-092529](https://user-images.githubusercontent.com/14342127/60633722-894a0000-9e3e-11e9-85c7-dde841d56f40.png)
![WX20190704-092545](https://user-images.githubusercontent.com/14342127/60633725-8a7b2d00-9e3e-11e9-9fe8-a31e89d1ee3d.png)

**Comment by 5ini99** [comment]
将 bui.js 中 api.ajax 调用的 data 参数 body: "" 删掉即可
