### ISSUE TITLE
bui是怎么定义全局变量的，我应该如何获取到input的值并且操作呢？

### ISSUE THREAD

**Issue by aohanhongzhi** [imouou/BUI-Guide#94]
bui是怎么定义全局变量的，我应该如何获取到input的值并且操作呢？

**Comment by imouou** [comment]
在index.js 定义的变量, 并且不在 bui.ready 里面, 其它页面都可以访问到全局变量, 获取input 值, 使用jquery或者 dom 的方式都可以 $("#inputid").val()  ; 就跟web开发一样, 没有改变开发者的习惯.
