### ISSUE TITLE
List组件中如何进行异步操作？

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#95]
作者，您好。
我想在template返回前执行一些异步操作（如ajax查询，此查询依赖template中的data），这种做法合不合理？如果合理，怎么才能实现呢？

**Comment by imouou** [comment]
不合理, 控件里面都是同步的, 你可以在 ajax 拿到数据以后再进行控件初始化.

**Comment by shoppingzh** [comment]
ajax要取的数据取决于List组件本次加载到的数据，所以这种方法无法满足我的需求。

看来只能将所有数据一次性返回。

**Comment by imouou** [comment]
list 已经包含异步数据了, 为何无法满足你的需求

**Comment by shoppingzh** [comment]
简单地说就是List加载完数据后并不能马上渲染，在渲染前还需要加载一些额外的数据，而这些额外数据的加载又依赖于List获取到的数据。（其实完全可以在后端将这些额外的数据一起封装返回，在这里仅仅是讨论一下这种方法的可行性）

**Comment by imouou** [comment]
明白, 但这种设计不是很合理, 也不通用, 可以基于 bui.scroll 去封装一个你自己需求的 list

**Comment by shoppingzh** [comment]
嗯嗯，我也觉得是的。但是既然这种思路本身不是很合理，也就没有必要这么做了。
scroll组件真的好用，用的很爽。

**Comment by imouou** [comment]
嗯, list 就是基于scroll组件来的, 所以要重新封装一个符合自己需求的也是没问题的.

**Comment by shoppingzh** [comment]
作者您以前从事过iOS或Android开发吧，在大学的时候做过Android，现在在公司搞过iOS，感觉BUI里的一些概念以及组件的设计与客户端开发不谋而合，总之就是很爽，希望持续更新。

**Comment by imouou** [comment]
没有这方面的经验, 只有一些设计及前端方面的, 如果能够融汇贯通, 说明真的懂了. ^_^
