### ISSUE TITLE
表单在超出屏幕之后，键盘输入会遮挡输入框

### ISSUE THREAD

**Issue by wangyankun33** [imouou/BUI-Guide#97]
![image](https://user-images.githubusercontent.com/19883375/61345633-8dd3d700-a888-11e9-9ec7-61c1bbf38461.png)
![image](https://user-images.githubusercontent.com/19883375/61345642-96c4a880-a888-11e9-848a-cc761703846b.png)

**Comment by imouou** [comment]
官网文档的帮助里面，常见问题有这方面的答案 http://www.easybui.com/guide/#/help

**Comment by wangyankun33** [comment]
@imouou  我看了其中2个解决方案，在手机上点击输入框之后，正常，但是在点了返回按钮之后，页面没有滚动回来，底部是一片空白!
![1563343105(1)](https://user-images.githubusercontent.com/19883375/61350823-676b6700-a89b-11e9-9845-597f74893710.png)

**Comment by wangyankun33** [comment]
![1563343105(1)](https://user-images.githubusercontent.com/19883375/61350864-8c5fda00-a89b-11e9-9e4f-c50cf8238e8d.png)
