### ISSUE TITLE
页面路由跳转后，没有动态加载页面

### ISSUE THREAD

**Issue by wangyankun33** [imouou/BUI-Guide#98]
图片地址，需要把 blob: 也带上
blob:http://www.gif5.net/9bf71dd5-1b91-4147-b508-123179fd9013

**Comment by imouou** [comment]
图片没有看到，不过单页路由跳转以后，默认都会执行define里面的回调一次的

**Comment by wangyankun33** [comment]
请看附件 



2603109625@qq.com
 
发件人： 王小o
发送时间： 2019-07-19 09:57
收件人： imouou/BUI-Guide
抄送： wangyankun33; Author
主题： Re: [imouou/BUI-Guide] 页面路由跳转后，没有动态加载页面 (#98)
图片没有看到，不过单页路由跳转以后，默认都会执行define里面的回调一次的

**Comment by imouou** [comment]
没有收到附件，你可以尝试在跳转以后的页面里面 输出一下看看， 跳转以后有执行的
