### ISSUE TITLE
router单页，bui.load跳转到其他页面，返回后router.getCurrentPage() 为null

### ISSUE THREAD

**Issue by wuweiit** [imouou/BUI-Guide#99]
router单页，bui.load跳转到其他页面，返回后router.getCurrentPage() 为null。

问题原因分析：可能是返回没有切换last。

**Comment by imouou** [comment]
貌似没有这个方法哦，router.currentPage() 才是， 但1.5以后的版本已经不需要这个了，直接使用 router.$ 替换 $ 选择器就可以了，比方：
以前 $("#id").height(300); 在模块里面 router.$("#id").height(300)  这样就可以只针对当前模块，不会跟其它页面造成冲突。

**Comment by wuweiit** [comment]
都是官网文档里看到的函数，另辟蹊径解决了：
```
 var currentPage = router.currentPage();
 if(!currentPage){// 当前页面的上级
      currentPage = $(".shengmingxinxi-form").parents('.bui-router-item')[0];
} 
```
新页面尝试下你给的方法，现在几十个页面改router.$ 有点痛苦，哈哈。

BUI项目真的很牛，坑还是多，填完了坑一定是快速开发WebAPP利器，加油哦。

**Comment by shoppingzh** [comment]
这里为什么不使用BUI提供的api呢？router.$()才是应该调用的api啊。
```
currentPage = $(".shengmingxinxi-form").parents('.bui-router-item')[0];
```
这种方式虽然能达到目标，但是不严谨。举例说明，假设BUI以后将路由item的类名从bui-router-item改为了bui-router-entity，那么你现有的代码将全部无法工作。不依赖BUI的底层数据，而直接使用BUI抛出的上层接口，这是正确做法，原因很简单，因为这些底层数据有可能是可配置的，因而不能硬编码依赖这些可配置的数据。

此外，几十个页面的更改在VSCode下简直不是问题，使用搜索功能搜索并替换即可。
